/* ── Accounting labels — THE central UI-string object ─────────────────
   BRIEF-accounting-rebuild-final.md: accounting screens are English
   only, and every UI string lives here — never hardcoded inline.
   Vendor/item/master-data VALUES render exactly as in the SN masters;
   only UI chrome comes from this object.

   AR_DICT below is the APPROVED Arabic dictionary from the brief's
   appendix, stored for a future language switch — DO NOT build the
   switch now. Statuses and lifecycle labels remain English in all
   languages. */

/** KWD, 3 decimals, English label — accounting screens never follow the
 *  i18n language (the shared kd() does, and would render د.ك here). */
export function kwd(v: number | string | null | undefined): string {
  const n = Number(v || 0)
  return `KD ${n.toLocaleString("en-US", { minimumFractionDigits: 3, maximumFractionDigits: 3 })}`
}

export const L = {
  app: {
    title: "Accounting",
    logout: "Log out",
    retry: "Retry",
    loadError: "Couldn't load data — check the connection.",
    noAccess: "This area is for the accountant. Ask the office to enable your account.",
  },
  nav: {
    audit: "Audit queue",
    poRegister: "PO register",
    bundling: "Bundling",
    bundles: "Bundles",
    grn: "GRN",
  },
  tabs: {
    asphalt: "Asphalt",
    materials: "Materials",
  },
  status: {
    matched: "Matched",
    dispatched_not_received: "Dispatched, not received",
    received_not_dispatched: "Received, not dispatched",
    not_received: "Not received",
    no_po: "No PO",
  },
  register: {
    heading: "PO register",
    search: "Search PO number, SN number, or vendor…",
    noPos: "No active POs.",
    noPosHint: "POs arrive from the SpectroNova import or manual entry.",
    pickPo: "Pick a PO to see its line balances.",
    noDate: "no date",
    noLines: "No lines registered yet — balances are tracked per line.",
    line: (n: number) => `Line ${n}`,
    lumpSum: "Lump sum",
    ordered: "Ordered",
    bundled: "Bundled",
    pendingShort: (n: string) => `${n} in draft`,
    remaining: "Remaining",
    over: "Over by",
    complete: "Complete",
    nearLimit: "Nearing limit",
    addLines: "Add lines",
    addLinesHint: "SN imports carry PO headers only — type the lines once per PO.",
    colItem: "Item / description",
    colQty: "Qty",
    colUnit: "UOM",
    colRate: "Unit price",
    colRemarks: "Remarks (laying method…)",
    addRow: "Add row",
    save: "Save lines",
    saving: "Saving…",
    saveFailed: "Couldn't save — check the entries and try again.",
    itemRequired: "Every line needs an item description.",
    showingPos: (n: number, total: number) => `showing ${n} of ${total} POs`,
  },
  bundling: {
    heading: "Bundling",
    hint: "A bundle bills matched notes against exactly one PO line.",
    empty: "No matched notes waiting to be bundled.",
    emptyHint: "Drive notes to Matched in the audit queue first.",
    colPick: "Select",
    colNote: "Delivery note no.",
    colDate: "Date",
    colSite: "Site",
    colItem: "Item",
    colQty: "Qty",
    selected: (n: number, q: string) => `${n} selected · qty ${q}`,
    linePick: "PO line",
    linePlaceholder: "Pick the PO line to bill against",
    lineOption: (po: string, line: number, item: string, rem: string) =>
      `${po} · line ${line} · ${item}${rem ? ` (remaining ${rem})` : ""}`,
    suggested: "Pre-set to the last line used for this item on this PO — confirm or change.",
    create: "Create bundle",
    creating: "Creating…",
    created: (no: string) => `Bundle ${no} created as draft.`,
    needSelection: "Select at least one note.",
    needLine: "Pick a PO line.",
    createFailed: "Couldn't create the bundle",
    noLines: "No active PO lines on this channel — register lines on the PO first.",
  },
  bundles: {
    heading: "Bundles",
    empty: "No bundles yet.",
    emptyHint: "Create one from the Bundling screen.",
    colBundle: "Bundle",
    colPoLine: "PO / line",
    colQtyAmount: "Qty · amount",
    colStatus: "Status",
    colSnRef: "SN reference",
    pendingImport: "pending import",
    adjusting: "adjusting",
    lifecycle: { draft: "Draft", verified: "Verified", published: "Published" },
    verify: "Verify",
    publish: "Publish",
    demote: "Back to draft",
    del: "Delete",
    confirmPublish: (no: string, amount: string) =>
      `Publish ${no} (${amount})? Published bundles are immutable — corrections need an adjusting bundle.`,
    confirmDelete: (no: string) => `Delete draft ${no}?`,
    actionFailed: "Action failed",
  },
  detail: {
    notFound: "Bundle not found.",
    back: "Back to bundles",
    grn: "GRN",
    grnSoon: "GRN printing lands in the next step.",
    excel: "Excel",
    fieldSupplier: "Supplier",
    fieldPo: "PO Number",
    fieldPoLine: "PO Line",
    fieldDate: "Delivery Date",
    colDn: "Supplier DN No.",
    colItemCode: "Item Code",
    colQty: "Qty",
    colUom: "UOM",
    colUnitPrice: "Unit Price",
    colAmount: "Amount",
    totals: (notes: number, q: string) => `${notes} notes · qty ${q} · total KWD`,
    previewNote: "Preview — this bundle is not published and is not visible to SN staff.",
    importedTitle: "Imported to SN",
    importedRef: "SN reference",
    importPlaceholder: "INVSI/… and/or Stock_Receipt/…",
    importSave: "Save",
    importSaving: "Saving…",
    importNeedRef: "Enter the SN reference.",
    importFailed: "Couldn't save the import confirmation",
    adjustOpen: "Create adjusting bundle",
    adjustHint: "Enter the qty difference per note (negative = deduction); zero rows are skipped. The adjusting bundle publishes on its own.",
    adjustLine: "Target PO line",
    adjustCreate: "Create adjusting bundle",
    adjustCreating: "Creating…",
    adjustNeedDiff: "Enter at least one non-zero difference.",
    adjustNeedLine: "Pick the target PO line.",
    adjustFailed: "Couldn't create the adjusting bundle",
    adjustsRef: (no: string) => `Adjusts ${no}`,
  },
  grn: {
    heading: "GRN documents",
    disclaimer: "COPRI supporting document — not a SpectroNova record",
    footerLine: "COPRI Construction Enterprises W.L.L. · Founded 1969",
    title: "Goods Received Note",
    perBundle: "GRN for a bundle",
    perNote: "GRN for individual notes",
    bundlePick: "Pick a bundle",
    print: "Print",
    printing: "Preparing…",
    printCount: (n: number) => `Print GRN (${n})`,
    day: "Day",
    site: "Site",
    po: "PO",
    allSites: "All sites",
    allPos: "All POs",
    noBundles: "No bundles yet.",
    noNotes: "No received notes match the filters.",
    selectAll: (n: number) => `Select all (${n})`,
    popupBlocked: "Allow pop-ups to print the document.",
    mintFailed: "Couldn't allocate GRN numbers",
    fGrnNo: "GRN No.",
    fDnNo: "Delivery note no.",
    fDate: "Receipt date",
    fProject: "Project",
    fSite: "Site",
    fPo: "PO",
    fSupplier: "Supplier",
    fItem: "Item",
    fQty: "Qty received",
    fUnit: "UOM",
    fWo: "Work order",
    fSubcontractor: "Subcontractor",
    fBundle: "Bundle",
    fPoLine: "PO line",
    fUnitPrice: "Unit price (KWD)",
    fItemCode: "Item code",
    colIdx: "#",
    colDn: "DN no.",
    colDate: "Date",
    colSite: "Site",
    colQty: "Qty",
    colAmount: "Amount (KWD)",
    totals: "Total",
    sigEngineer: "Site engineer",
    sigAccountant: "Accountant",
    showingCap: (n: number) => `Showing the first ${n} — narrow the filters.`,
  },
  audit: {
    heading: "Audit queue",
    hint: "Unmatched notes cannot be bundled.",
    oldestUnmatched: (days: number) => `oldest unmatched: ${days}d`,
    colNote: "Delivery note no.",
    colSite: "Site",
    colVendor: "Vendor",
    colItem: "Item",
    colQtyT: "Qty (t)",
    colQty: "Qty",
    colStatus: "Status",
    empty: "No delivery notes here yet.",
    emptyHint: "Notes appear as the plant dispatches and sites capture deliveries.",
    showing: (n: number, total: number) => `showing ${n} of ${total}`,
    all: "All",
  },
} as const

/* Approved Arabic dictionary (brief appendix) — future switch only. */
export const AR_DICT = {
  bundle: "تجميعة",
  bundles: "التجميعات",
  bundling: "التجميع",
  auditQueue: "قائمة التدقيق",
  audit: "تدقيق",
  deliveryNote: "سند تسليم",
  supplierDnNo: "رقم سند تسليم المورد",
  grn: "سند استلام بضاعة",
  grnDisclaimer: "مستند داعم من كوبري — ليس سجلاً في SpectroNova",
  po: "أمر شراء",
  poLine: "بند أمر الشراء",
  qty: "الكمية",
  uom: "الوحدة",
  unitPrice: "سعر الوحدة",
  amount: "المبلغ",
  tons: "طن",
  kwd: "د.ك",
  // Statuses and lifecycle labels remain ENGLISH in all languages.
} as const
