/* ── Accounting labels — THE central UI-string object ─────────────────
   BRIEF-accounting-rebuild-final.md: accounting screens are English
   only, and every UI string lives here — never hardcoded inline.
   Vendor/item/master-data VALUES render exactly as in the SN masters;
   only UI chrome comes from this object.

   AR_DICT below is the APPROVED Arabic dictionary from the brief's
   appendix, stored for a future language switch — DO NOT build the
   switch now. Statuses and lifecycle labels remain English in all
   languages. */

/** KWD, 3 decimals, English label — accounting screens never follow the
 *  i18n language (the shared kd() does, and would render د.ك here). */
export function kwd(v: number | string | null | undefined): string {
  const n = Number(v || 0)
  return `KD ${n.toLocaleString("en-US", { minimumFractionDigits: 3, maximumFractionDigits: 3 })}`
}

export const L = {
  app: {
    title: "Accounting",
    logout: "Log out",
    retry: "Retry",
    loadError: "Couldn't load data — check the connection.",
    noAccess: "This area is for the accountant. Ask the office to enable your account.",
    emailRequired: "Accounting needs the email sign-in — the interim PIN can't read draft bundles. Sign out and log in with your email account.",
    allCostCenters: "All cost centers",
  },
  nav: {
    audit: "Audit queue",
    poRegister: "PO register",
    bundling: "Bundling",
    bundles: "Bundles",
    grn: "GRN",
    snSync: "SN sync",
  },
  tabs: {
    asphalt: "Asphalt",
    materials: "Materials",
  },
  status: {
    matched: "Matched",
    dispatched_not_received: "Dispatched, not received",
    received_not_dispatched: "Received, not dispatched",
    not_received: "Not received",
    no_po: "No PO",
  },
  /* Materials channel overrides: a capture IS the receival (the site
     engineer records externally supplied goods on arrival), so there is
     no second leg to "match" — the statuses describe the accounting
     lifecycle. Storage tokens unchanged (bundling keys off 'matched'). */
  statusMat: {
    matched: "Mapped & approved",
    not_received: "Pending daily batch",
    no_po: "No PO — exception",
  },
  register: {
    heading: "PO register",
    search: "Search PO number, SN number, or vendor…",
    noPos: "No active POs.",
    noPosHint: "POs arrive from the SpectroNova import or manual entry.",
    pickPo: "Pick a PO to see its line balances.",
    noDate: "no date",
    noLines: "No lines registered yet — balances are tracked per line.",
    line: (n: number) => `Line ${n}`,
    lumpSum: "Lump sum",
    ordered: "Ordered",
    bundled: "Bundled",
    pendingShort: (n: string) => `${n} in draft`,
    remaining: "Remaining",
    over: "Over by",
    complete: "Complete",
    nearLimit: "Nearing limit",
    addLines: "Add lines",
    addLinesHint: "SN imports carry PO headers only — type the lines once per PO.",
    colItem: "Item / description",
    colQty: "Qty",
    colUnit: "UOM",
    colRate: "Unit price",
    colRemarks: "Remarks (laying method…)",
    addRow: "Add row",
    save: "Save lines",
    saving: "Saving…",
    saveFailed: "Couldn't save — check the entries and try again.",
    itemRequired: "Every line needs an item description.",
    showingPos: (n: number, total: number) => `showing ${n} of ${total} POs`,
    // SN mirror mode (pipeline_settings.po_source = sn)
    sourceSn: "Source: SpectroNova mirror — POs and lines are read-only here; received quantities come from SN stock receipts.",
    sourceLegacy: "Source: app PO register (imported + manual). SpectroNova mirror is available once the sync is switched on.",
    showClosed: "Show closed POs",
    badgeFa: "Fixed asset",
    badgeClosed: "Closed",
    received: "Received (SN)",
    receipts: (n: number) => `${n} receipt${n === 1 ? "" : "s"}`,
    searchSn: "Search PO number, supplier, or department…",
  },
  bundling: {
    heading: "Bundling",
    hint: "A bundle bills matched notes against exactly one PO line.",
    empty: "No matched notes waiting to be bundled.",
    emptyHint: "Drive notes to Matched in the audit queue first.",
    colPick: "Select",
    colNote: "Delivery note no.",
    colDate: "Date",
    colSite: "Site",
    colItem: "Item",
    colQty: "Qty",
    selected: (n: number, q: string) => `${n} selected · qty ${q}`,
    linePick: "PO line",
    linePlaceholder: "Pick the PO line to bill against",
    lineOption: (po: string, line: number, item: string, rem: string) =>
      `${po} · line ${line} · ${item}${rem ? ` (remaining ${rem})` : ""}`,
    suggested: "Pre-set to the last line used for this item on this PO — confirm or change.",
    create: "Create bundle",
    creating: "Creating…",
    created: (no: string) => `Bundle ${no} created as draft.`,
    needSelection: "Select at least one note.",
    needLine: "Pick a PO line.",
    createFailed: "Couldn't create the bundle",
    noLines: "No active PO lines on this channel — register lines on the PO first.",
  },
  bundles: {
    heading: "Bundles",
    empty: "No bundles yet.",
    emptyHint: "Create one from the Bundling screen.",
    colBundle: "Bundle",
    colPoLine: "PO / line",
    colQtyAmount: "Qty · amount",
    colStatus: "Status",
    colSnRef: "SN reference",
    pendingImport: "pending import",
    adjusting: "adjusting",
    lifecycle: { draft: "Draft", verified: "Verified", published: "Published" },
    verify: "Verify",
    publish: "Publish",
    demote: "Back to draft",
    del: "Delete",
    confirmPublish: (no: string, amount: string) =>
      `Publish ${no} (${amount})? Published bundles are immutable — corrections need an adjusting bundle.`,
    confirmDelete: (no: string) => `Delete draft ${no}?`,
    actionFailed: "Action failed",
    showingCap: (n: number) => `Showing the newest ${n} bundles.`,
  },
  sync: {
    heading: "SpectroNova sync",
    intro: "Read-only mirror of SN purchase orders, vendors, items, stock receipts and supplier invoices. Runs nightly; admins can run it now.",
    lastRun: "Last run",
    never: "never",
    status: "Status",
    running: "running",
    counts: "Mirror",
    pos: "POs", receipts: "receipts", invoices: "invoices", vendors: "vendors", items: "items",
    syncNow: "Sync now (quick)",
    syncFull: "Full sync",
    syncing: "Starting…",
    started: (id: number) => `Run #${id} started — progress updates below.`,
    startFailed: "Couldn't start the sync",
    notAdmin: "Only admins can start a sync.",
    stages: "Stages",
    colStage: "Stage", colFetched: "Fetched", colNew: "New", colChanged: "Changed", colSame: "Unchanged", colMissed: "Missed", colErrors: "Errors", colTime: "Time",
    alerts: "Alerts",
    noAlerts: "No open alerts.",
    dismiss: "Dismiss",
    dismissed: "Alert dismissed.",
    showDismissed: "Show dismissed",
    kind: {
      po_revised: "PO revised in SN",
      po_discovered_via_receipt: "PO found via receipt (walk missed it)",
      po_discovered_via_invoice: "PO found via invoice (walk missed it)",
      sr_revised: "Stock receipt revised",
      invoice_revised: "Invoice revised",
      header_line_mismatch: "PO header ≠ Σ lines",
      parse_failure: "Could not parse a document",
      walk_stopped: "Forward walk stopped",
      auth_failed: "SN sign-in failed",
      stage_error: "Sync stage failed",
    } as Record<string, string>,
    runs: "Recent runs",
    poSource: "PO source for register & bundling",
    poSourceSn: "SpectroNova mirror",
    poSourceLegacy: "App register (legacy)",
    poSourceHint: "Switch with: update pipeline_settings set value = '{\"source\":\"sn\"}' where key = 'po_source' (see migration 0065).",
    recon: "Legacy ↔ SN reconciliation",
    reconHint: "Report only — nothing is deleted. Match key = SN PO number on the imported app PO.",
    matched: "matched", legacyOnly: "legacy only", snOnly: "SN only",
    reconEmpty: "Nothing to reconcile yet — run the first sync.",
    colBucket: "Bucket", colApp: "App PO", colSn: "SN PO", colVendor: "Vendor / supplier", colValue: "App value", colSnNet: "SN net", colDelta: "Δ", colBundles: "Bundles",
    showing: (n: number, total: number) => `showing ${n} of ${total}`,
  },
  detail: {
    notFound: "Bundle not found.",
    back: "Back to bundles",
    grn: "GRN",
    grnSoon: "GRN printing lands in the next step.",
    excel: "Excel",
    fieldSupplier: "Supplier",
    fieldPo: "PO Number",
    fieldPoLine: "PO Line",
    fieldDate: "Delivery Date",
    colDn: "Supplier DN No.",
    colItemCode: "Item Code",
    colQty: "Qty",
    colUom: "UOM",
    colUnitPrice: "Unit Price",
    colAmount: "Amount",
    totals: (notes: number, q: string) => `${notes} notes · qty ${q} · total KWD`,
    previewNote: "Preview — this bundle is not published and is not visible to SN staff.",
    importedTitle: "Imported to SN",
    importedRef: "SN reference",
    importPlaceholder: "INVSI/… and/or Stock_Receipt/…",
    importSave: "Save",
    importSaving: "Saving…",
    importNeedRef: "Enter the SN reference.",
    importFailed: "Couldn't save the import confirmation",
    adjustOpen: "Create adjusting bundle",
    adjustHint: "Enter the qty difference per note (negative = deduction); zero rows are skipped. The adjusting bundle publishes on its own.",
    adjustLine: "Target PO line",
    adjustCreate: "Create adjusting bundle",
    adjustCreating: "Creating…",
    adjustNeedDiff: "Enter at least one non-zero difference.",
    adjustNeedLine: "Pick the target PO line.",
    adjustFailed: "Couldn't create the adjusting bundle",
    adjustsRef: (no: string) => `Adjusts ${no}`,
  },
  grn: {
    heading: "GRN documents",
    disclaimer: "COPRI supporting document — not a SpectroNova record",
    footerLine: "COPRI Construction Enterprises W.L.L. · Founded 1969",
    title: "Goods Received Note",
    perBundle: "GRN for a bundle",
    perNote: "GRN for individual notes",
    bundlePick: "Pick a published bundle",
    publishedOnly: "GRNs are issued for published bundles only.",
    print: "Print",
    printing: "Preparing…",
    printCount: (n: number) => `Print GRN (${n})`,
    day: "Day",
    site: "Site",
    po: "PO",
    allSites: "All sites",
    allPos: "All POs",
    noBundles: "No bundles yet.",
    noNotes: "No received notes match the filters.",
    selectAll: (n: number) => `Select all (${n})`,
    popupBlocked: "Allow pop-ups to print the document.",
    mintFailed: "Couldn't allocate GRN numbers",
    fGrnNo: "GRN No.",
    fDnNo: "Delivery note no.",
    fDate: "Receipt date",
    fProject: "Project",
    fSite: "Site",
    fPo: "PO",
    fSupplier: "Supplier",
    fItem: "Item",
    fQty: "Qty received",
    fUnit: "UOM",
    fWo: "Work order",
    fSubcontractor: "Subcontractor",
    fBundle: "Bundle",
    fPoLine: "PO line",
    fUnitPrice: "Unit price (KWD)",
    fItemCode: "Item code",
    colIdx: "#",
    colDn: "DN no.",
    colDate: "Date",
    colSite: "Site",
    colQty: "Qty",
    colAmount: "Amount (KWD)",
    totals: "Total",
    sigEngineer: "Site engineer",
    sigAccountant: "Accountant",
    showingCap: (n: number) => `Showing the first ${n} — narrow the filters.`,
  },
  sn: {
    title: "COPRI — SpectroNova data page",
    intro: "Read-only: published bundles for manual entry into SpectroNova. Recording the import reference is the only edit.",
    tokenPrompt: "Enter the access token provided by the COPRI office.",
    tokenLabel: "Access token",
    tokenGo: "Open",
    tokenBad: "Invalid token — contact the COPRI office.",
    loadFailed: "Couldn't load — check the connection and retry.",
    pending: (n: number) => `Pending import (${n})`,
    pendingNone: "Nothing pending — every published bundle is recorded. ✓",
    pendingLine: (bundle: string, po: string, lines: number, published: string) =>
      `${bundle} · ${po} · ${lines} lines · published ${published}`,
    filters: "Filter & download",
    from: "Delivery date from",
    to: "Delivery date to",
    po: "PO",
    site: "Site",
    allPos: "All POs",
    allSites: "All sites",
    csv: (n: number) => `Download CSV / Excel (${n} rows)`,
    noRows: "No rows match the filters.",
    imported: "Imported",
    pendingBadge: "Pending import",
    publishedOn: (d: string) => `published ${d}`,
    reference: "SN reference",
    refPlaceholder: "INVSI/… and/or Stock_Receipt/…",
    refSave: "Record import",
    refSaving: "Saving…",
    refNeed: "Enter the SN reference.",
    refFailed: "Couldn't save — try again.",
    totalKwd: "Total (KWD)",
  },
  audit: {
    heading: "Audit queue",
    hint: "Unmatched notes cannot be bundled.",
    hintMat: "Captures bundle once mapped to a PO line in the daily batch; exceptions need a PO or a resolution.",
    oldestUnmatched: (days: number) => `oldest unmatched: ${days}d`,
    colNote: "Delivery note no.",
    colSite: "Site",
    colVendor: "Vendor",
    colItem: "Item",
    colQtyT: "Qty (t)",
    colQty: "Qty",
    colStatus: "Status",
    empty: "No delivery notes here yet.",
    emptyHint: "Notes appear as the plant dispatches and sites capture deliveries.",
    showing: (n: number, total: number) => `showing ${n} of ${total}`,
    all: "All",
    rowHint: "Click a note to open its full record.",
    ccNoNotes: "Delivery notes are tagged by project — this division cost center has none.",
  },
  note: {
    /* Note detail (screen 1b) — values render exactly as stored (Arabic
       master data stays Arabic); only these chrome strings are English. */
    headingAsphalt: "Delivery note",
    headingMaterial: "Materials receipt",
    back: "Back to audit queue",
    notFound: "Note not found.",
    dispatchCard: "Dispatch — clerk entry",
    receiptCard: "Receipt — site entry",
    captureCard: "Capture — site engineer entry",
    accountingCard: "Accounting",
    notReceivedTitle: "Not received yet",
    notReceivedLink: (eng: string) => `The receipt link went to ${eng} (from the clerk's entry).`,
    notReceivedNoEng: "The clerk's entry names no engineer — no receipt link was sent for this load.",
    multiReceipts: "Multiple receipt entries — the latest one decides the match.",
    fDispatchedAt: "Dispatched at",
    fLoadNo: "Load # (day)",
    fCompany: "Company",
    fProject: "Project",
    fContract: "Contract",
    fWo: "Work order",
    fPlant: "Plant",
    fMix: "Mix",
    fWeight: "Weight (t)",
    fTemp: "Temp (°C)",
    fTruck: "Truck",
    fDriver: "Driver",
    fDriverPhone: "Driver phone",
    fNaqel: "Transporter",
    fSite: "Site",
    fBlock: "Block / from-km",
    fStreet: "Street / to-km",
    fLocType: "Location type",
    fClerk: "Clerk",
    fStatus: "Status",
    fRemarks: "Remarks",
    fMisc: "Misc load (متفرقات)",
    fNotify: "Engineer (link recipient)",
    fFollowup: "Follow-up flagged",
    yes: "Yes",
    rReceivedAt: "Received at",
    rEngineer: "Engineer",
    rDecision: "Decision",
    rWeight: "Arrival weight (t)",
    rTemp: "Arrival temp (°C)",
    rWo: "Work order",
    rRemarks: "Remarks",
    mCapturedAt: "Captured at",
    mReceiver: "Receiver (site engineer)",
    mCategory: "Category",
    mMaterial: "Material",
    mQty: "Qty",
    mUnit: "UOM",
    mSupplier: "Supplier",
    mSubcontractor: "Subcontractor",
    mPhoto: "Paper receipt photo",
    mOpenPhoto: "Open full size",
    aApproval: "Approval",
    aApprovedBy: "Approved by",
    aApprovedAt: "Approved at",
    aException: "Exception note",
    aNoPo: "No-PO flag",
    bundleTitle: "Bundled in",
    notBundled: "Not in any bundle yet.",
    adjustment: "adjustment",
  },
} as const

/* Approved Arabic dictionary (brief appendix) — future switch only. */
export const AR_DICT = {
  bundle: "تجميعة",
  bundles: "التجميعات",
  bundling: "التجميع",
  auditQueue: "قائمة التدقيق",
  audit: "تدقيق",
  deliveryNote: "سند تسليم",
  supplierDnNo: "رقم سند تسليم المورد",
  grn: "سند استلام بضاعة",
  grnDisclaimer: "مستند داعم من كوبري — ليس سجلاً في SpectroNova",
  po: "أمر شراء",
  poLine: "بند أمر الشراء",
  qty: "الكمية",
  uom: "الوحدة",
  unitPrice: "سعر الوحدة",
  amount: "المبلغ",
  tons: "طن",
  kwd: "د.ك",
  // Statuses and lifecycle labels remain ENGLISH in all languages.
} as const
