#!/usr/bin/env python3
"""SpectroNova PO importer — Slice 1 of the commitment pipeline (0018).

Reads the per-department "Purchase Order (PO)*.xlsx" exports under
"Accounting raw data/spectronova/", maps each file to its canonical cost
center via tools/import-map.json (Fouad confirms the mapping once, then
sets "confirmed": true), cross-checks the mapping, and emits:

  Accounting raw data/output/po_import_report.md   — always
  Accounting raw data/output/po_import.sql         — only when confirmed

The SQL is idempotent (`on conflict (number) do nothing`) and is pasted
into the Supabase SQL editor like a migration. Commitment numbers are
"{cc_code}-{PO Number}" because SpectroNova PO sequences restart per
department — the raw number alone would collide across files.

Cross-check (the PO exports carry NO department column): each
department's Delivery Note file references its POs by number
(PurchaseOrderNumber). A PO number claimed by a DIFFERENT department's
DN file is flagged instead of trusted silently.

Vendors resolve by vendor_norm() equality against the canonical vendors
table; unmatched names are INSERTED as kind='supplier' with an import
note (the report lists them for the later master cleanup). Internal
profit-center suppliers map through vendor_aliases in import-map.json.

Usage:  python tools/import_pos.py            (from the repo root)
"""
import json
import re
import sys
from datetime import datetime
from pathlib import Path

try:
    from openpyxl import load_workbook
except ImportError:
    sys.exit("openpyxl missing — run: pip install --user openpyxl")

ROOT = Path(__file__).resolve().parent.parent
RAW = ROOT / "Accounting raw data" / "spectronova"
OUT = ROOT / "Accounting raw data" / "output"
MAP = ROOT / "tools" / "import-map.json"

PO_HEADER = ["Document Date", "PO Number", "Subject", "PR Number", "Supplier",
             "Posted Status", "Currency", "Net Amount", "Type", "Action", "ClosedDate"]


def sql_quote(s):
    return "'" + str(s).replace("'", "''") + "'"


def norm_name(s):
    # mirror of vendor_norm() in 0013: lowercase, non-alnum (latin+arabic) → space
    return re.sub(r"[^0-9a-z؀-ۿ]+", " ", str(s or "").lower()).strip()


def parse_date(v):
    if isinstance(v, datetime):
        return v.date().isoformat()
    for fmt in ("%d %b %Y", "%d/%m/%Y", "%Y-%m-%d"):
        try:
            return datetime.strptime(str(v).strip(), fmt).date().isoformat()
        except ValueError:
            pass
    return None


def read_rows(path):
    wb = load_workbook(path, read_only=True, data_only=True)
    ws = wb[wb.sheetnames[0]]
    rows = list(ws.iter_rows(values_only=True))
    wb.close()
    # locate the header row (exports sometimes carry title rows above it)
    for i, r in enumerate(rows):
        cells = [str(c).strip() if c is not None else "" for c in r]
        if "PO Number" in cells:
            header = cells
            return header, [dict(zip(header, rr)) for rr in rows[i + 1:]
                            if any(c is not None and str(c).strip() for c in rr)]
    raise ValueError(f"{path.name}: header row not found")


def main():
    cfg = json.loads(MAP.read_text(encoding="utf-8"))
    confirmed = bool(cfg.get("confirmed"))
    aliases = {k: v for k, v in cfg.get("vendor_aliases", {}).items() if not k.startswith("_")}
    OUT.mkdir(exist_ok=True)

    # DN cross-reference: PO number → set of cost centers whose DN file cites it
    dn_claims = {}
    for fname, cc in cfg.get("dn_files", {}).items():
        p = RAW / fname
        if not p.exists():
            continue
        wb = load_workbook(p, read_only=True, data_only=True)
        ws = wb[wb.sheetnames[0]]
        rows = list(ws.iter_rows(values_only=True))
        wb.close()
        hdr = None
        for i, r in enumerate(rows):
            cells = [str(c).strip() if c is not None else "" for c in r]
            if "PurchaseOrderNumber" in cells:
                hdr = cells
                col = hdr.index("PurchaseOrderNumber")
                for rr in rows[i + 1:]:
                    v = rr[col] if col < len(rr) else None
                    if v and str(v).strip():
                        dn_claims.setdefault(str(v).strip(), set()).add(cc)
                break

    report = ["# PO import report — generated " + datetime.now().isoformat(timespec="seconds"), ""]
    if not confirmed:
        report += ["> ⚠️ **import-map.json is NOT confirmed** — no SQL was emitted.",
                   "> Review the mapping below, set `\"confirmed\": true`, re-run.", ""]

    sql = ["-- PO import — generated by tools/import_pos.py " + datetime.now().isoformat(timespec="seconds"),
           "-- Idempotent: re-runs skip rows whose commitment number already exists.",
           "begin;", ""]
    totals, all_numbers, unmatched_vendors, flags = {}, {}, {}, []

    for fname, meta in cfg["po_files"].items():
        p = RAW / fname
        cc = meta["cost_center"]
        if not p.exists():
            flags.append(f"MISSING FILE: {fname}")
            continue
        header, rows = read_rows(p)
        if header[:len(PO_HEADER)] != PO_HEADER:
            flags.append(f"{fname}: unexpected header {header} — file skipped")
            continue
        n_ok = n_skip = 0
        val = 0.0
        sql.append(f"-- ── {fname} → {meta['department']} (cost center {cc}) ──")
        for r in rows:
            po_no = str(r.get("PO Number") or "").strip()
            supplier = str(r.get("Supplier") or "").strip()
            subject = str(r.get("Subject") or "").strip()
            posted = str(r.get("Posted Status") or "").strip()
            date = parse_date(r.get("Document Date"))
            try:
                amount = float(str(r.get("Net Amount") or "0").replace(",", ""))
            except ValueError:
                amount = 0.0
            if not po_no or not supplier:
                n_skip += 1
                flags.append(f"{fname}: row missing PO number/supplier skipped ({po_no!r}/{supplier!r})")
                continue
            if posted != "Posted":
                n_skip += 1
                flags.append(f"{fname}: {po_no} is '{posted}' — not imported (register it via the portal when approved)")
                continue
            if amount <= 0:
                n_skip += 1
                flags.append(f"{fname}: {po_no} has non-positive amount {amount} — skipped")
                continue
            claims = dn_claims.get(po_no, set())
            if claims and cc not in claims:
                flags.append(f"CROSS-CHECK: {fname}:{po_no} is cited by DN of {sorted(claims)} but mapped to {cc}")
            all_numbers.setdefault(po_no, []).append(cc)

            vendor = aliases.get(supplier, supplier)
            unmatched_vendors.setdefault(vendor, 0)
            unmatched_vendors[vendor] += 1
            number = f"{cc}-{po_no}"
            desc = subject or f"PO {po_no}"
            created = f"{sql_quote(date)}::date" if date else "now()"
            sql.append(
                "insert into vendors (name, kind, notes)\n"
                f"  select {sql_quote(vendor)}, 'supplier', 'SpectroNova PO import {cfg.get('export_date','')}'\n"
                f"  where not exists (select 1 from vendors where vendor_norm(name) = vendor_norm({sql_quote(vendor)}));"
            )
            sql.append(
                "insert into commitments (number, ctype, request_id, cost_center_id, vendor_id,\n"
                "    description, value, origin, source_ref, source_file, created_by, created_at)\n"
                f"select {sql_quote(number)}, 'LPO', null,\n"
                f"    (select id from cost_centers where code = {sql_quote(cc)}),\n"
                f"    (select id from vendors where vendor_norm(name) = vendor_norm({sql_quote(vendor)}) limit 1),\n"
                f"    {sql_quote(desc)}, {amount}, 'import', {sql_quote(po_no)}, {sql_quote(fname)},\n"
                f"    '(import)', {created}\n"
                f"on conflict (number) do nothing;"
            )
            n_ok += 1
            val += amount
        totals[fname] = (meta["department"], cc, n_ok, n_skip, val)
        sql.append("")

    sql += ["commit;", ""]

    # collisions: same raw PO number mapped to several departments is EXPECTED
    # (per-dept sequences) — the cc prefix keeps commitment numbers unique.
    collisions = {k: v for k, v in all_numbers.items() if len(v) > 1}

    report += ["## Mapping & counts", "",
               "| File | Department | CC | imported | skipped | value (KWD) |", "|---|---|---|---|---|---|"]
    for f, (dep, cc, ok, sk, v) in totals.items():
        report.append(f"| {f} | {dep} | {cc} | {ok} | {sk} | {v:,.3f} |")
    report += ["", f"Raw PO numbers shared across departments (expected, prefixed away): {len(collisions)}", ""]
    if flags:
        report += ["## Flags", ""] + [f"- {x}" for x in flags] + [""]
    report += ["## Vendors referenced (resolve/merge in the master cleanup)", ""]
    for v, n in sorted(unmatched_vendors.items(), key=lambda kv: -kv[1]):
        report.append(f"- {v} ×{n}")

    (OUT / "po_import_report.md").write_text("\n".join(report), encoding="utf-8")
    print(f"report -> {OUT / 'po_import_report.md'}")
    if confirmed:
        (OUT / "po_import.sql").write_text("\n".join(sql), encoding="utf-8")
        print(f"SQL    -> {OUT / 'po_import.sql'}  (paste in the Supabase SQL editor)")
    else:
        print("SQL not emitted — set \"confirmed\": true in tools/import-map.json after review.")


if __name__ == "__main__":
    main()
