# -*- coding: utf-8 -*-
"""Close the finished Expressway work orders — mirrors 0043 for Hawalli.

Source: `بيان اوامر العمل.xls`, sheet `جميع اوامر العمل` (trailing space —
the CURRENT vintage; see qm_expw_wo.read_register for why the other copies
must not be used). Column `حالة امر العمل نهائي/جزئي` is authoritative:
'نهائي' means the work order is finished, 'جزئي' that it is still running.

As in 0043, the exact Arabic wording is preserved in the changelog so the
decision is auditable, and `closed` stays reversible per work order in the
UI. Writes supabase/migrations/0053_qm_expw_close_wos.sql.
"""
import sys, io, os, re, json, unicodedata, collections

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

import xlrd

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
DESK = os.path.join(os.path.expanduser("~"), "Desktop")
REGISTER = os.path.join(DESK, "ExpresswaysQMbackfill", "الدفعة", "بيان اوامر العمل.xls")
WO_JSON = os.path.join(DESK, "quantities-backfill", "expw-wo-data.json")
MIG = os.path.join(REPO, "supabase", "migrations", "0053_qm_expw_close_wos.sql")


def clean(v):
    if v is None:
        return ""
    s = "".join(ch for ch in str(v) if unicodedata.category(ch) != "Cf")
    return re.sub(r"\s+", " ", s.replace("\xa0", " ").replace("ـ", "")).strip()


def esc(s):
    return str(s).replace("'", "''")


def main():
    bk = xlrd.open_workbook(REGISTER)
    names = {clean(n): n for n in bk.sheet_names()}
    sh = bk.sheet_by_name(names["جميع اوامر العمل"])
    hdr = next(r for r in range(20) if clean(sh.cell_value(r, 0)) == "امر العمل")
    cols = {}
    for c in range(sh.ncols):
        h = clean(sh.cell_value(hdr, c))
        for key, needle in (("status", "حالة امر العمل"),
                            ("finish", "الانتهاء الفعلي")):
            if h.startswith(needle) and key not in cols:
                cols[key] = c

    reg = {}
    for r in range(hdr + 1, sh.nrows):
        w = clean(sh.cell_value(r, 0))
        w = w[:-2] if w.endswith(".0") else w
        if not w.isdigit():
            continue
        reg[int(w)] = {k: clean(sh.cell_value(r, c)) for k, c in cols.items()}

    imported = {w["wo"] for w in json.load(open(WO_JSON, encoding="utf-8"))}
    closed = sorted(w for w, v in reg.items()
                    if v["status"].startswith("نهائي") and w in imported)
    open_ = sorted(w for w, v in reg.items()
                   if not v["status"].startswith("نهائي") and w in imported)

    print("register rows: %d | statuses: %s" %
          (len(reg), dict(collections.Counter(v["status"] for v in reg.values()))))
    print("closing %d: %s" % (len(closed), closed))
    print("left open %d: %s" % (len(open_), open_))
    print("in register but not imported: %s" % sorted(set(reg) - imported))

    body = ["""-- 0053_qm_expw_close_wos — GENERATED by tools/qm_expw_close_wos.py.
-- Closes the %d Expressway work orders the register reports as finished
-- (حالة امر العمل = 'نهائي'); the %d still 'جزئي' stay open: %s.
-- Source: بيان اوامر العمل.xls, sheet 'جميع اوامر العمل' (the current
-- vintage — the other copies are older snapshots in which several of these
-- were still جزئي). The Arabic wording is kept in the changelog so the
-- decision is auditable, and `closed` remains reversible per WO in the UI.
-- Idempotent. Paste after 0050.
do $qmexpwcl$
declare
  v_contract bigint;
  v_k bigint;
begin
  select id into v_contract from qm_contracts where code = 'EXPW';
  if v_contract is null then raise exception 'run 0047 first'; end if;
""" % (len(closed), len(open_), ", ".join(str(w) for w in open_))]

    for w in closed:
        r = reg[w]
        label = r["status"] + (" — الانتهاء الفعلي %s" % r["finish"] if r["finish"] else "")
        body.append("""
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = %d;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — %s', 'expw-register');
  end if;""" % (w, esc(label)))

    body.append("\nend $qmexpwcl$;\n")
    out = "\n".join(body)
    open(MIG, "w", encoding="utf-8").write(out)
    print("\nWROTE: %s  (%.1f KB)" % (os.path.basename(MIG), len(out.encode()) / 1024))


if __name__ == "__main__":
    main()
