-- 0053_qm_expw_close_wos — GENERATED by tools/qm_expw_close_wos.py.
-- Closes the 58 Expressway work orders the register reports as finished
-- (حالة امر العمل = 'نهائي'); the 7 still 'جزئي' stay open: 23, 63, 64, 65, 66, 67, 68.
-- Source: بيان اوامر العمل.xls, sheet 'جميع اوامر العمل' (the current
-- vintage — the other copies are older snapshots in which several of these
-- were still جزئي). The Arabic wording is kept in the changelog so the
-- decision is auditable, and `closed` remains reversible per WO in the UI.
-- Idempotent. Paste after 0050.
do $qmexpwcl$
declare
  v_contract bigint;
  v_k bigint;
begin
  select id into v_contract from qm_contracts where code = 'EXPW';
  if v_contract is null then raise exception 'run 0047 first'; end if;


  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 1;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 15/12/2024', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 2;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 04/02/2025', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 02/02/2025', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 4;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 19/01/2025', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 5;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 29/04/2025', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 6;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 02/02/2025', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 7;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 28/02/2025', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 9;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 29/8/2025', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 10;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 29/03/2025', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 11;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 28/02/2025', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 12;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 14/03/2025', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 13;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 27/04/2025', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 14;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 14/05/2025', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 15;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 04/06/2025', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 16;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 23/6/2025', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 17;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 18/04/2025', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 18;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 25/6/2025', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 19;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 29/7/2025', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 20;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 45998.0', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 21;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 15/6/2025', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 22;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 21/04/2025', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 24;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 46000.0', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 25;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 45663.0', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 26;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 03/06/2025', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 27;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 45969.0', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 28;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 23/7/2025', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 29;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 45786.0', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 30;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 30/11/2025', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 31;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 45666.0', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 32;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 45786.0', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 33;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 20/8/2025', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 34;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 45846.0', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 35;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 45971.0', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 36;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 45786.0', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 37;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 46174.0', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 38;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 28/10/2025', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 39;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 26/2/2026', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 40;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 45939.0', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 41;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 31/10/2025', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 42;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 16/2/2026', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 43;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 17/12/2025', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 44;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 29/10/2025', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 45;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 45698.0', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 46;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 28/2/2026', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 47;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 45757.0', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 48;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 45698.0', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 49;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 13/10/2025', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 50;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 46001.0', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 51;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 45879.0', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 52;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 12/4/206', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 53;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 21/10/2025', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 54;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 28/10/2025', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 55;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 29/12/2025', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 56;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 16/5/2026', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 57;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 46146.0', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 58;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 46146.0', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 59;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 28/2/2026', 'expw-register');
  end if;

  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 60;
  if v_k is not null and not (select closed from qm_kashefs where id = v_k) then
    update qm_kashefs set closed = true where id = v_k;
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_k, 'update', 'closed', '', 'false', 'true — نهائي — الانتهاء الفعلي 14/5/2026', 'expw-register');
  end if;

end $qmexpwcl$;
