-- 0058_qm_expw_tadqiq_wo3 — GENERATED by tools/qm_expw_tadqiq.py, do not hand-edit.
-- INCREMENTAL: work orders [3] only (their sheet is named 'الطلبات'); no allocation block. Paste after 0051/0054.
-- Expressway طلبات التدقيق: 1117 requests / 2907 lines / KD 13,130,242.140 pre-pct,
-- from the unnumbered طلبات التدقيق sheet of each أمر عمل workbook.
-- Booked against 'كوبري — تنفيذ ذاتي' — those sheets carry no subcontractor and
-- qm_tadqiq.vendor_id is NOT NULL (Fouad, 2026-08-16). opening = false:
-- these are real dated requests, so the executed trend is real history.
-- Allocations are seeded allocated := executed per work-order line.
-- Paste 0050 first (the work orders these attach to).
-- Idempotent: each request is guarded on (kashef, serial, date, note) — the note
-- carries an occurrence suffix «(n)» when a serial repeats.

do $qmexpwtd$
declare
  v_contract bigint;
  v_vendor bigint;
  v_k bigint;
  v_t bigint;
  v_item bigint;
  v_line bigint;
begin
  select id into v_contract from qm_contracts where code = 'EXPW';
  if v_contract is null then raise exception 'run 0047 first'; end if;
  select id into v_vendor from vendors where name = 'كوبري — تنفيذ ذاتي';
  if v_vendor is null then
    insert into vendors (name, kind, internal, notes)
    values ('كوبري — تنفيذ ذاتي', 'internal', true,
            'quantities module — COPRI self-performed works (backfill)')
    returning id into v_vendor;
  end if;
  update vendors set qm_subcontractor = true where id = v_vendor and not qm_subcontractor;

  -- ── أمر عمل 3 — طلب تدقيق 214 (2024-12-24) ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null and not exists (select 1 from qm_tadqiq where kashef_id = v_k and serial_no = '214' and tadqiq_date = date '2024-12-24' and note = 'استيراد تاريخي — الطرق السريعة' and not opening) then
    insert into qm_tadqiq (kashef_id, vendor_id, tadqiq_date, street_no, note, opening, serial_no)
    values (v_k, v_vendor, date '2024-12-24', '', 'استيراد تاريخي — الطرق السريعة', false, '214') returning id into v_t;
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 2 and band = 16 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 16/2 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 3157, false, false);
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 215 (2024-12-24) ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null and not exists (select 1 from qm_tadqiq where kashef_id = v_k and serial_no = '215' and tadqiq_date = date '2024-12-24' and note = 'استيراد تاريخي — الطرق السريعة' and not opening) then
    insert into qm_tadqiq (kashef_id, vendor_id, tadqiq_date, street_no, note, opening, serial_no)
    values (v_k, v_vendor, date '2024-12-24', '', 'استيراد تاريخي — الطرق السريعة', false, '215') returning id into v_t;
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 2 and band = 17 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 17/2 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 19979.7, false, false);
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 216 (2024-12-24) ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null and not exists (select 1 from qm_tadqiq where kashef_id = v_k and serial_no = '216' and tadqiq_date = date '2024-12-24' and note = 'استيراد تاريخي — الطرق السريعة' and not opening) then
    insert into qm_tadqiq (kashef_id, vendor_id, tadqiq_date, street_no, note, opening, serial_no)
    values (v_k, v_vendor, date '2024-12-24', '', 'استيراد تاريخي — الطرق السريعة', false, '216') returning id into v_t;
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 2 and band = 23 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 23/2 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 182.52, false, false);
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 220 (2025-03-01) ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null and not exists (select 1 from qm_tadqiq where kashef_id = v_k and serial_no = '220' and tadqiq_date = date '2025-03-01' and note = 'استيراد تاريخي — الطرق السريعة' and not opening) then
    insert into qm_tadqiq (kashef_id, vendor_id, tadqiq_date, street_no, note, opening, serial_no)
    values (v_k, v_vendor, date '2025-03-01', '', 'استيراد تاريخي — الطرق السريعة', false, '220') returning id into v_t;
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 2 and band = 33 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 33/2 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 19979.7, false, false);
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 222 (2024-12-25) ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null and not exists (select 1 from qm_tadqiq where kashef_id = v_k and serial_no = '222' and tadqiq_date = date '2024-12-25' and note = 'استيراد تاريخي — الطرق السريعة' and not opening) then
    insert into qm_tadqiq (kashef_id, vendor_id, tadqiq_date, street_no, note, opening, serial_no)
    values (v_k, v_vendor, date '2024-12-25', '', 'استيراد تاريخي — الطرق السريعة', false, '222') returning id into v_t;
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 2 and band = 96 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 96/2 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 4624, false, false);
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 223 (2024-12-28) ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null and not exists (select 1 from qm_tadqiq where kashef_id = v_k and serial_no = '223' and tadqiq_date = date '2024-12-28' and note = 'استيراد تاريخي — الطرق السريعة' and not opening) then
    insert into qm_tadqiq (kashef_id, vendor_id, tadqiq_date, street_no, note, opening, serial_no)
    values (v_k, v_vendor, date '2024-12-28', '', 'استيراد تاريخي — الطرق السريعة', false, '223') returning id into v_t;
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 2 and band = 101 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 101/2 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 35.49, false, false);
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 224 (2024-12-26) ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null and not exists (select 1 from qm_tadqiq where kashef_id = v_k and serial_no = '224' and tadqiq_date = date '2024-12-26' and note = 'استيراد تاريخي — الطرق السريعة' and not opening) then
    insert into qm_tadqiq (kashef_id, vendor_id, tadqiq_date, street_no, note, opening, serial_no)
    values (v_k, v_vendor, date '2024-12-26', '', 'استيراد تاريخي — الطرق السريعة', false, '224') returning id into v_t;
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 12 and band = 66 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 66/12 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 360, false, false);
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 225 (2024-12-28) ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null and not exists (select 1 from qm_tadqiq where kashef_id = v_k and serial_no = '225' and tadqiq_date = date '2024-12-28' and note = 'استيراد تاريخي — الطرق السريعة' and not opening) then
    insert into qm_tadqiq (kashef_id, vendor_id, tadqiq_date, street_no, note, opening, serial_no)
    values (v_k, v_vendor, date '2024-12-28', '', 'استيراد تاريخي — الطرق السريعة', false, '225') returning id into v_t;
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 12 and band = 79 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 79/12 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 117, false, false);
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 226 (2024-12-25) ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null and not exists (select 1 from qm_tadqiq where kashef_id = v_k and serial_no = '226' and tadqiq_date = date '2024-12-25' and note = 'استيراد تاريخي — الطرق السريعة' and not opening) then
    insert into qm_tadqiq (kashef_id, vendor_id, tadqiq_date, street_no, note, opening, serial_no)
    values (v_k, v_vendor, date '2024-12-25', '', 'استيراد تاريخي — الطرق السريعة', false, '226') returning id into v_t;
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 12 and band = 105 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 105/12 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 53, false, false);
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 227 (2024-12-25) ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null and not exists (select 1 from qm_tadqiq where kashef_id = v_k and serial_no = '227' and tadqiq_date = date '2024-12-25' and note = 'استيراد تاريخي — الطرق السريعة' and not opening) then
    insert into qm_tadqiq (kashef_id, vendor_id, tadqiq_date, street_no, note, opening, serial_no)
    values (v_k, v_vendor, date '2024-12-25', '', 'استيراد تاريخي — الطرق السريعة', false, '227') returning id into v_t;
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 12 and band = 106 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 106/12 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 117, false, false);
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 228 (2024-12-29) ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null and not exists (select 1 from qm_tadqiq where kashef_id = v_k and serial_no = '228' and tadqiq_date = date '2024-12-29' and note = 'استيراد تاريخي — الطرق السريعة' and not opening) then
    insert into qm_tadqiq (kashef_id, vendor_id, tadqiq_date, street_no, note, opening, serial_no)
    values (v_k, v_vendor, date '2024-12-29', '', 'استيراد تاريخي — الطرق السريعة', false, '228') returning id into v_t;
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 5 and band = 98 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 98/5 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 3690, false, false);
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 300 (2025-02-01) ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null and not exists (select 1 from qm_tadqiq where kashef_id = v_k and serial_no = '300' and tadqiq_date = date '2025-02-01' and note = 'استيراد تاريخي — الطرق السريعة' and not opening) then
    insert into qm_tadqiq (kashef_id, vendor_id, tadqiq_date, street_no, note, opening, serial_no)
    values (v_k, v_vendor, date '2025-02-01', '', 'استيراد تاريخي — الطرق السريعة', false, '300') returning id into v_t;
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 5 and band = 62 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 62/5 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 3504, false, false);
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 291 (2025-01-01) ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null and not exists (select 1 from qm_tadqiq where kashef_id = v_k and serial_no = '291' and tadqiq_date = date '2025-01-01' and note = 'استيراد تاريخي — الطرق السريعة' and not opening) then
    insert into qm_tadqiq (kashef_id, vendor_id, tadqiq_date, street_no, note, opening, serial_no)
    values (v_k, v_vendor, date '2025-01-01', '', 'استيراد تاريخي — الطرق السريعة', false, '291') returning id into v_t;
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 5 and band = 62 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 62/5 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 1120, false, false);
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 290 (2025-01-01) ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null and not exists (select 1 from qm_tadqiq where kashef_id = v_k and serial_no = '290' and tadqiq_date = date '2025-01-01' and note = 'استيراد تاريخي — الطرق السريعة' and not opening) then
    insert into qm_tadqiq (kashef_id, vendor_id, tadqiq_date, street_no, note, opening, serial_no)
    values (v_k, v_vendor, date '2025-01-01', '', 'استيراد تاريخي — الطرق السريعة', false, '290') returning id into v_t;
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 2 and band = 25 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 25/2 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 384.705, false, false);
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 6 and band = 26 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 26/6 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 159, false, false);
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 292 (2025-01-01) ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null and not exists (select 1 from qm_tadqiq where kashef_id = v_k and serial_no = '292' and tadqiq_date = date '2025-01-01' and note = 'استيراد تاريخي — الطرق السريعة' and not opening) then
    insert into qm_tadqiq (kashef_id, vendor_id, tadqiq_date, street_no, note, opening, serial_no)
    values (v_k, v_vendor, date '2025-01-01', '', 'استيراد تاريخي — الطرق السريعة', false, '292') returning id into v_t;
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 5 and band = 51 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 51/5 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 177, false, false);
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 301 (2025-05-01) ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null and not exists (select 1 from qm_tadqiq where kashef_id = v_k and serial_no = '301' and tadqiq_date = date '2025-05-01' and note = 'استيراد تاريخي — الطرق السريعة' and not opening) then
    insert into qm_tadqiq (kashef_id, vendor_id, tadqiq_date, street_no, note, opening, serial_no)
    values (v_k, v_vendor, date '2025-05-01', '', 'استيراد تاريخي — الطرق السريعة', false, '301') returning id into v_t;
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 5 and band = 28 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 28/5 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 400, false, false);
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 306 (2025-05-01) ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null and not exists (select 1 from qm_tadqiq where kashef_id = v_k and serial_no = '306' and tadqiq_date = date '2025-05-01' and note = 'استيراد تاريخي — الطرق السريعة' and not opening) then
    insert into qm_tadqiq (kashef_id, vendor_id, tadqiq_date, street_no, note, opening, serial_no)
    values (v_k, v_vendor, date '2025-05-01', '', 'استيراد تاريخي — الطرق السريعة', false, '306') returning id into v_t;
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 5 and band = 60 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 60/5 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 5120, false, false);
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 340 (2025-01-13) ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null and not exists (select 1 from qm_tadqiq where kashef_id = v_k and serial_no = '340' and tadqiq_date = date '2025-01-13' and note = 'استيراد تاريخي — الطرق السريعة' and not opening) then
    insert into qm_tadqiq (kashef_id, vendor_id, tadqiq_date, street_no, note, opening, serial_no)
    values (v_k, v_vendor, date '2025-01-13', '', 'استيراد تاريخي — الطرق السريعة', false, '340') returning id into v_t;
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 5 and band = 1 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 1/5 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 85.362, false, false);
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 339 (2025-01-14) ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null and not exists (select 1 from qm_tadqiq where kashef_id = v_k and serial_no = '339' and tadqiq_date = date '2025-01-14' and note = 'استيراد تاريخي — الطرق السريعة' and not opening) then
    insert into qm_tadqiq (kashef_id, vendor_id, tadqiq_date, street_no, note, opening, serial_no)
    values (v_k, v_vendor, date '2025-01-14', '', 'استيراد تاريخي — الطرق السريعة', false, '339') returning id into v_t;
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 5 and band = 12 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 12/5 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 13.8, false, false);
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 505 (2025-07-01) ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null and not exists (select 1 from qm_tadqiq where kashef_id = v_k and serial_no = '505' and tadqiq_date = date '2025-07-01' and note = 'استيراد تاريخي — الطرق السريعة' and not opening) then
    insert into qm_tadqiq (kashef_id, vendor_id, tadqiq_date, street_no, note, opening, serial_no)
    values (v_k, v_vendor, date '2025-07-01', '', 'استيراد تاريخي — الطرق السريعة', false, '505') returning id into v_t;
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 2 and band = 38 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 38/2 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 1768, false, false);
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 503 (2025-02-02) ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null and not exists (select 1 from qm_tadqiq where kashef_id = v_k and serial_no = '503' and tadqiq_date = date '2025-02-02' and note = 'استيراد تاريخي — الطرق السريعة' and not opening) then
    insert into qm_tadqiq (kashef_id, vendor_id, tadqiq_date, street_no, note, opening, serial_no)
    values (v_k, v_vendor, date '2025-02-02', '', 'استيراد تاريخي — الطرق السريعة', false, '503') returning id into v_t;
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 2 and band = 17 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 17/2 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 3372, false, false);
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 2 and band = 33 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 33/2 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 3372, false, false);
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 501 (2025-02-02) ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null and not exists (select 1 from qm_tadqiq where kashef_id = v_k and serial_no = '501' and tadqiq_date = date '2025-02-02' and note = 'استيراد تاريخي — الطرق السريعة' and not opening) then
    insert into qm_tadqiq (kashef_id, vendor_id, tadqiq_date, street_no, note, opening, serial_no)
    values (v_k, v_vendor, date '2025-02-02', '', 'استيراد تاريخي — الطرق السريعة', false, '501') returning id into v_t;
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 5 and band = 62 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 62/5 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 1760, false, false);
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 502 (2025-02-02) ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null and not exists (select 1 from qm_tadqiq where kashef_id = v_k and serial_no = '502' and tadqiq_date = date '2025-02-02' and note = 'استيراد تاريخي — الطرق السريعة' and not opening) then
    insert into qm_tadqiq (kashef_id, vendor_id, tadqiq_date, street_no, note, opening, serial_no)
    values (v_k, v_vendor, date '2025-02-02', '', 'استيراد تاريخي — الطرق السريعة', false, '502') returning id into v_t;
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 5 and band = 98 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 98/5 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 2250, false, false);
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 506 (2025-02-02) ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null and not exists (select 1 from qm_tadqiq where kashef_id = v_k and serial_no = '506' and tadqiq_date = date '2025-02-02' and note = 'استيراد تاريخي — الطرق السريعة' and not opening) then
    insert into qm_tadqiq (kashef_id, vendor_id, tadqiq_date, street_no, note, opening, serial_no)
    values (v_k, v_vendor, date '2025-02-02', '', 'استيراد تاريخي — الطرق السريعة', false, '506') returning id into v_t;
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 5 and band = 60 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 60/5 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 10249, false, false);
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 504 (2025-02-02) ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null and not exists (select 1 from qm_tadqiq where kashef_id = v_k and serial_no = '504' and tadqiq_date = date '2025-02-02' and note = 'استيراد تاريخي — الطرق السريعة' and not opening) then
    insert into qm_tadqiq (kashef_id, vendor_id, tadqiq_date, street_no, note, opening, serial_no)
    values (v_k, v_vendor, date '2025-02-02', '', 'استيراد تاريخي — الطرق السريعة', false, '504') returning id into v_t;
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 5 and band = 5 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 5/5 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 24.37, false, false);
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 5 and band = 12 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 12/5 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 35, false, false);
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 507 (2025-02-02) ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null and not exists (select 1 from qm_tadqiq where kashef_id = v_k and serial_no = '507' and tadqiq_date = date '2025-02-02' and note = 'استيراد تاريخي — الطرق السريعة' and not opening) then
    insert into qm_tadqiq (kashef_id, vendor_id, tadqiq_date, street_no, note, opening, serial_no)
    values (v_k, v_vendor, date '2025-02-02', '', 'استيراد تاريخي — الطرق السريعة', false, '507') returning id into v_t;
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 6 and band = 39 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 39/6 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 10, false, false);
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 6 and band = 54 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 54/6 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 4, false, false);
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 508 (2025-02-02) ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null and not exists (select 1 from qm_tadqiq where kashef_id = v_k and serial_no = '508' and tadqiq_date = date '2025-02-02' and note = 'استيراد تاريخي — الطرق السريعة' and not opening) then
    insert into qm_tadqiq (kashef_id, vendor_id, tadqiq_date, street_no, note, opening, serial_no)
    values (v_k, v_vendor, date '2025-02-02', '', 'استيراد تاريخي — الطرق السريعة', false, '508') returning id into v_t;
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 6 and band = 68 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 68/6 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 6, false, false);
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 6 and band = 69 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 69/6 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 3, false, false);
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 12 and band = 1 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 1/12 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 120, false, false);
  end if;

end $qmexpwtd$;
