-- 0059_qm_expw_exec_split_wo3 — GENERATED by tools/qm_expw_exec_split.py, do not hand-edit.
-- INCREMENTAL: work orders [3] only. Paste after their qm_expw_tadqiq --wo migration.
-- Reassigns the Expressway طلبات التدقيق (0051, all on «كوبري — تنفيذ ذاتي») to the
-- subcontractor whose payment certificate absorbed each request, using
-- دفعات مقاولي الباطن read as a time series (see the tool docstring and
-- quantities-backfill/expw-exec-report.md). Quantities and dates are unchanged;
-- only vendor_id moves. 27 of 1117 requests touched, 5 split across vendors.
-- Also inserts the 6 requests 0051's guard skipped (note «… (2)»).
-- Idempotent. Paste after 0054 (needs its vendor rows).
-- part 1 of 1
do $qmexpwex$
declare
  v_contract bigint;
  v_copri bigint;
  v_k bigint;
  v_t bigint;
  v_item bigint;
  v_s0 bigint;
begin
  select id into v_contract from qm_contracts where code = 'EXPW';
  if v_contract is null then raise exception 'run 0047 first'; end if;
  select id into v_copri from vendors where name = 'كوبري — تنفيذ ذاتي';
  if v_copri is null then raise exception 'COPRI pseudo-vendor missing'; end if;

  select id into v_s0 from vendors where id = 10;
  if v_s0 is null then raise exception 'vendor 10 missing'; end if;


  -- ── أمر عمل 3 — طلب تدقيق 214 (2024-12-24) → vendors.id 10 ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null then
    select id into v_t from qm_tadqiq where kashef_id = v_k and serial_no = '214' and tadqiq_date = date '2024-12-24' and note = 'استيراد تاريخي — الطرق السريعة' and not opening and vendor_id in (v_copri, v_s0) order by (vendor_id = v_s0) desc limit 1;
    if v_t is null then raise exception 'WO 3 طلب 214 missing — run 0051 first'; end if;
    begin
      update qm_tadqiq set vendor_id = v_s0 where id = v_t and vendor_id <> v_s0;
    end;
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 215 (2024-12-24) → vendors.id 10 ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null then
    select id into v_t from qm_tadqiq where kashef_id = v_k and serial_no = '215' and tadqiq_date = date '2024-12-24' and note = 'استيراد تاريخي — الطرق السريعة' and not opening and vendor_id in (v_copri, v_s0) order by (vendor_id = v_s0) desc limit 1;
    if v_t is null then raise exception 'WO 3 طلب 215 missing — run 0051 first'; end if;
    begin
      update qm_tadqiq set vendor_id = v_s0 where id = v_t and vendor_id <> v_s0;
    end;
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 216 (2024-12-24) → vendors.id 10 ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null then
    select id into v_t from qm_tadqiq where kashef_id = v_k and serial_no = '216' and tadqiq_date = date '2024-12-24' and note = 'استيراد تاريخي — الطرق السريعة' and not opening and vendor_id in (v_copri, v_s0) order by (vendor_id = v_s0) desc limit 1;
    if v_t is null then raise exception 'WO 3 طلب 216 missing — run 0051 first'; end if;
    begin
      update qm_tadqiq set vendor_id = v_s0 where id = v_t and vendor_id <> v_s0;
    end;
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 220 (2025-03-01) → vendors.id 10 ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null then
    select id into v_t from qm_tadqiq where kashef_id = v_k and serial_no = '220' and tadqiq_date = date '2025-03-01' and note = 'استيراد تاريخي — الطرق السريعة' and not opening and vendor_id in (v_copri, v_s0) order by (vendor_id = v_s0) desc limit 1;
    if v_t is null then raise exception 'WO 3 طلب 220 missing — run 0051 first'; end if;
    begin
      update qm_tadqiq set vendor_id = v_s0 where id = v_t and vendor_id <> v_s0;
    end;
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 222 (2024-12-25) → vendors.id 10 + كوبري — تنفيذ ذاتي ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null then
    select id into v_t from qm_tadqiq where kashef_id = v_k and serial_no = '222' and tadqiq_date = date '2024-12-25' and note = 'استيراد تاريخي — الطرق السريعة' and not opening and vendor_id in (v_copri, v_s0) order by (vendor_id = v_s0) desc limit 1;
    if v_t is null then raise exception 'WO 3 طلب 222 missing — run 0051 first'; end if;
    begin
      update qm_tadqiq set vendor_id = v_s0 where id = v_t and vendor_id <> v_s0;
      delete from qm_tadqiq_lines where tadqiq_id = v_t;
      select id into v_item from qm_bop_items where contract_id = v_contract and bab = 2 and band = 96 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 96/2 missing'; end if;
      insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 2924, false, false);
    end;
    delete from qm_tadqiq where kashef_id = v_k and serial_no = '222' and tadqiq_date = date '2024-12-25' and note = 'استيراد تاريخي — الطرق السريعة' and not opening and vendor_id = v_copri;
    insert into qm_tadqiq (kashef_id, vendor_id, tadqiq_date, street_no, note, opening, serial_no)
    values (v_k, v_copri, date '2024-12-25', '', 'استيراد تاريخي — الطرق السريعة', false, '222') returning id into v_t;
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 2 and band = 96 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 96/2 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 1700, false, false);
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 223 (2024-12-28) → vendors.id 10 + كوبري — تنفيذ ذاتي ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null then
    select id into v_t from qm_tadqiq where kashef_id = v_k and serial_no = '223' and tadqiq_date = date '2024-12-28' and note = 'استيراد تاريخي — الطرق السريعة' and not opening and vendor_id in (v_copri, v_s0) order by (vendor_id = v_s0) desc limit 1;
    if v_t is null then raise exception 'WO 3 طلب 223 missing — run 0051 first'; end if;
    begin
      update qm_tadqiq set vendor_id = v_s0 where id = v_t and vendor_id <> v_s0;
      delete from qm_tadqiq_lines where tadqiq_id = v_t;
      select id into v_item from qm_bop_items where contract_id = v_contract and bab = 2 and band = 101 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 101/2 missing'; end if;
      insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 23.1, false, false);
    end;
    delete from qm_tadqiq where kashef_id = v_k and serial_no = '223' and tadqiq_date = date '2024-12-28' and note = 'استيراد تاريخي — الطرق السريعة' and not opening and vendor_id = v_copri;
    insert into qm_tadqiq (kashef_id, vendor_id, tadqiq_date, street_no, note, opening, serial_no)
    values (v_k, v_copri, date '2024-12-28', '', 'استيراد تاريخي — الطرق السريعة', false, '223') returning id into v_t;
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 2 and band = 101 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 101/2 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 12.39, false, false);
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 224 (2024-12-26) → vendors.id 10 ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null then
    select id into v_t from qm_tadqiq where kashef_id = v_k and serial_no = '224' and tadqiq_date = date '2024-12-26' and note = 'استيراد تاريخي — الطرق السريعة' and not opening and vendor_id in (v_copri, v_s0) order by (vendor_id = v_s0) desc limit 1;
    if v_t is null then raise exception 'WO 3 طلب 224 missing — run 0051 first'; end if;
    begin
      update qm_tadqiq set vendor_id = v_s0 where id = v_t and vendor_id <> v_s0;
    end;
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 225 (2024-12-28) → vendors.id 10 ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null then
    select id into v_t from qm_tadqiq where kashef_id = v_k and serial_no = '225' and tadqiq_date = date '2024-12-28' and note = 'استيراد تاريخي — الطرق السريعة' and not opening and vendor_id in (v_copri, v_s0) order by (vendor_id = v_s0) desc limit 1;
    if v_t is null then raise exception 'WO 3 طلب 225 missing — run 0051 first'; end if;
    begin
      update qm_tadqiq set vendor_id = v_s0 where id = v_t and vendor_id <> v_s0;
    end;
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 226 (2024-12-25) → vendors.id 10 ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null then
    select id into v_t from qm_tadqiq where kashef_id = v_k and serial_no = '226' and tadqiq_date = date '2024-12-25' and note = 'استيراد تاريخي — الطرق السريعة' and not opening and vendor_id in (v_copri, v_s0) order by (vendor_id = v_s0) desc limit 1;
    if v_t is null then raise exception 'WO 3 طلب 226 missing — run 0051 first'; end if;
    begin
      update qm_tadqiq set vendor_id = v_s0 where id = v_t and vendor_id <> v_s0;
    end;
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 227 (2024-12-25) → vendors.id 10 ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null then
    select id into v_t from qm_tadqiq where kashef_id = v_k and serial_no = '227' and tadqiq_date = date '2024-12-25' and note = 'استيراد تاريخي — الطرق السريعة' and not opening and vendor_id in (v_copri, v_s0) order by (vendor_id = v_s0) desc limit 1;
    if v_t is null then raise exception 'WO 3 طلب 227 missing — run 0051 first'; end if;
    begin
      update qm_tadqiq set vendor_id = v_s0 where id = v_t and vendor_id <> v_s0;
    end;
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 228 (2024-12-29) → vendors.id 10 ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null then
    select id into v_t from qm_tadqiq where kashef_id = v_k and serial_no = '228' and tadqiq_date = date '2024-12-29' and note = 'استيراد تاريخي — الطرق السريعة' and not opening and vendor_id in (v_copri, v_s0) order by (vendor_id = v_s0) desc limit 1;
    if v_t is null then raise exception 'WO 3 طلب 228 missing — run 0051 first'; end if;
    begin
      update qm_tadqiq set vendor_id = v_s0 where id = v_t and vendor_id <> v_s0;
    end;
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 290 (2025-01-01) → vendors.id 10 ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null then
    select id into v_t from qm_tadqiq where kashef_id = v_k and serial_no = '290' and tadqiq_date = date '2025-01-01' and note = 'استيراد تاريخي — الطرق السريعة' and not opening and vendor_id in (v_copri, v_s0) order by (vendor_id = v_s0) desc limit 1;
    if v_t is null then raise exception 'WO 3 طلب 290 missing — run 0051 first'; end if;
    begin
      update qm_tadqiq set vendor_id = v_s0 where id = v_t and vendor_id <> v_s0;
    end;
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 291 (2025-01-01) → vendors.id 10 + كوبري — تنفيذ ذاتي ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null then
    select id into v_t from qm_tadqiq where kashef_id = v_k and serial_no = '291' and tadqiq_date = date '2025-01-01' and note = 'استيراد تاريخي — الطرق السريعة' and not opening and vendor_id in (v_copri, v_s0) order by (vendor_id = v_s0) desc limit 1;
    if v_t is null then raise exception 'WO 3 طلب 291 missing — run 0051 first'; end if;
    begin
      update qm_tadqiq set vendor_id = v_s0 where id = v_t and vendor_id <> v_s0;
      delete from qm_tadqiq_lines where tadqiq_id = v_t;
      select id into v_item from qm_bop_items where contract_id = v_contract and bab = 5 and band = 62 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 62/5 missing'; end if;
      insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 691.7544, false, false);
    end;
    delete from qm_tadqiq where kashef_id = v_k and serial_no = '291' and tadqiq_date = date '2025-01-01' and note = 'استيراد تاريخي — الطرق السريعة' and not opening and vendor_id = v_copri;
    insert into qm_tadqiq (kashef_id, vendor_id, tadqiq_date, street_no, note, opening, serial_no)
    values (v_k, v_copri, date '2025-01-01', '', 'استيراد تاريخي — الطرق السريعة', false, '291') returning id into v_t;
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 5 and band = 62 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 62/5 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 428.2456, false, false);
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 292 (2025-01-01) → vendors.id 10 ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null then
    select id into v_t from qm_tadqiq where kashef_id = v_k and serial_no = '292' and tadqiq_date = date '2025-01-01' and note = 'استيراد تاريخي — الطرق السريعة' and not opening and vendor_id in (v_copri, v_s0) order by (vendor_id = v_s0) desc limit 1;
    if v_t is null then raise exception 'WO 3 طلب 292 missing — run 0051 first'; end if;
    begin
      update qm_tadqiq set vendor_id = v_s0 where id = v_t and vendor_id <> v_s0;
    end;
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 300 (2025-02-01) → vendors.id 10 + كوبري — تنفيذ ذاتي ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null then
    select id into v_t from qm_tadqiq where kashef_id = v_k and serial_no = '300' and tadqiq_date = date '2025-02-01' and note = 'استيراد تاريخي — الطرق السريعة' and not opening and vendor_id in (v_copri, v_s0) order by (vendor_id = v_s0) desc limit 1;
    if v_t is null then raise exception 'WO 3 طلب 300 missing — run 0051 first'; end if;
    begin
      update qm_tadqiq set vendor_id = v_s0 where id = v_t and vendor_id <> v_s0;
      delete from qm_tadqiq_lines where tadqiq_id = v_t;
      select id into v_item from qm_bop_items where contract_id = v_contract and bab = 5 and band = 62 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 62/5 missing'; end if;
      insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 2164.203, false, false);
    end;
    delete from qm_tadqiq where kashef_id = v_k and serial_no = '300' and tadqiq_date = date '2025-02-01' and note = 'استيراد تاريخي — الطرق السريعة' and not opening and vendor_id = v_copri;
    insert into qm_tadqiq (kashef_id, vendor_id, tadqiq_date, street_no, note, opening, serial_no)
    values (v_k, v_copri, date '2025-02-01', '', 'استيراد تاريخي — الطرق السريعة', false, '300') returning id into v_t;
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 5 and band = 62 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 62/5 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 1339.797, false, false);
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 301 (2025-05-01) → vendors.id 10 ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null then
    select id into v_t from qm_tadqiq where kashef_id = v_k and serial_no = '301' and tadqiq_date = date '2025-05-01' and note = 'استيراد تاريخي — الطرق السريعة' and not opening and vendor_id in (v_copri, v_s0) order by (vendor_id = v_s0) desc limit 1;
    if v_t is null then raise exception 'WO 3 طلب 301 missing — run 0051 first'; end if;
    begin
      update qm_tadqiq set vendor_id = v_s0 where id = v_t and vendor_id <> v_s0;
    end;
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 306 (2025-05-01) → vendors.id 10 ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null then
    select id into v_t from qm_tadqiq where kashef_id = v_k and serial_no = '306' and tadqiq_date = date '2025-05-01' and note = 'استيراد تاريخي — الطرق السريعة' and not opening and vendor_id in (v_copri, v_s0) order by (vendor_id = v_s0) desc limit 1;
    if v_t is null then raise exception 'WO 3 طلب 306 missing — run 0051 first'; end if;
    begin
      update qm_tadqiq set vendor_id = v_s0 where id = v_t and vendor_id <> v_s0;
    end;
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 339 (2025-01-14) → vendors.id 10 ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null then
    select id into v_t from qm_tadqiq where kashef_id = v_k and serial_no = '339' and tadqiq_date = date '2025-01-14' and note = 'استيراد تاريخي — الطرق السريعة' and not opening and vendor_id in (v_copri, v_s0) order by (vendor_id = v_s0) desc limit 1;
    if v_t is null then raise exception 'WO 3 طلب 339 missing — run 0051 first'; end if;
    begin
      update qm_tadqiq set vendor_id = v_s0 where id = v_t and vendor_id <> v_s0;
    end;
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 340 (2025-01-13) → vendors.id 10 ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null then
    select id into v_t from qm_tadqiq where kashef_id = v_k and serial_no = '340' and tadqiq_date = date '2025-01-13' and note = 'استيراد تاريخي — الطرق السريعة' and not opening and vendor_id in (v_copri, v_s0) order by (vendor_id = v_s0) desc limit 1;
    if v_t is null then raise exception 'WO 3 طلب 340 missing — run 0051 first'; end if;
    begin
      update qm_tadqiq set vendor_id = v_s0 where id = v_t and vendor_id <> v_s0;
    end;
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 501 (2025-02-02) → vendors.id 10 + كوبري — تنفيذ ذاتي ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null then
    select id into v_t from qm_tadqiq where kashef_id = v_k and serial_no = '501' and tadqiq_date = date '2025-02-02' and note = 'استيراد تاريخي — الطرق السريعة' and not opening and vendor_id in (v_copri, v_s0) order by (vendor_id = v_s0) desc limit 1;
    if v_t is null then raise exception 'WO 3 طلب 501 missing — run 0051 first'; end if;
    begin
      update qm_tadqiq set vendor_id = v_s0 where id = v_t and vendor_id <> v_s0;
      delete from qm_tadqiq_lines where tadqiq_id = v_t;
      select id into v_item from qm_bop_items where contract_id = v_contract and bab = 5 and band = 62 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 62/5 missing'; end if;
      insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 1087.0426, false, false);
    end;
    delete from qm_tadqiq where kashef_id = v_k and serial_no = '501' and tadqiq_date = date '2025-02-02' and note = 'استيراد تاريخي — الطرق السريعة' and not opening and vendor_id = v_copri;
    insert into qm_tadqiq (kashef_id, vendor_id, tadqiq_date, street_no, note, opening, serial_no)
    values (v_k, v_copri, date '2025-02-02', '', 'استيراد تاريخي — الطرق السريعة', false, '501') returning id into v_t;
    select id into v_item from qm_bop_items where contract_id = v_contract and bab = 5 and band = 62 and coalesce(suffix,'') = '';
    if v_item is null then raise exception 'bop 62/5 missing'; end if;
    insert into qm_tadqiq_lines (tadqiq_id, bop_item_id, qty, out_of_kashef, over_allocation) values (v_t, v_item, 672.9574, false, false);
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 502 (2025-02-02) → vendors.id 10 ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null then
    select id into v_t from qm_tadqiq where kashef_id = v_k and serial_no = '502' and tadqiq_date = date '2025-02-02' and note = 'استيراد تاريخي — الطرق السريعة' and not opening and vendor_id in (v_copri, v_s0) order by (vendor_id = v_s0) desc limit 1;
    if v_t is null then raise exception 'WO 3 طلب 502 missing — run 0051 first'; end if;
    begin
      update qm_tadqiq set vendor_id = v_s0 where id = v_t and vendor_id <> v_s0;
    end;
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 503 (2025-02-02) → vendors.id 10 ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null then
    select id into v_t from qm_tadqiq where kashef_id = v_k and serial_no = '503' and tadqiq_date = date '2025-02-02' and note = 'استيراد تاريخي — الطرق السريعة' and not opening and vendor_id in (v_copri, v_s0) order by (vendor_id = v_s0) desc limit 1;
    if v_t is null then raise exception 'WO 3 طلب 503 missing — run 0051 first'; end if;
    begin
      update qm_tadqiq set vendor_id = v_s0 where id = v_t and vendor_id <> v_s0;
    end;
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 504 (2025-02-02) → vendors.id 10 ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null then
    select id into v_t from qm_tadqiq where kashef_id = v_k and serial_no = '504' and tadqiq_date = date '2025-02-02' and note = 'استيراد تاريخي — الطرق السريعة' and not opening and vendor_id in (v_copri, v_s0) order by (vendor_id = v_s0) desc limit 1;
    if v_t is null then raise exception 'WO 3 طلب 504 missing — run 0051 first'; end if;
    begin
      update qm_tadqiq set vendor_id = v_s0 where id = v_t and vendor_id <> v_s0;
    end;
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 505 (2025-07-01) → vendors.id 10 ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null then
    select id into v_t from qm_tadqiq where kashef_id = v_k and serial_no = '505' and tadqiq_date = date '2025-07-01' and note = 'استيراد تاريخي — الطرق السريعة' and not opening and vendor_id in (v_copri, v_s0) order by (vendor_id = v_s0) desc limit 1;
    if v_t is null then raise exception 'WO 3 طلب 505 missing — run 0051 first'; end if;
    begin
      update qm_tadqiq set vendor_id = v_s0 where id = v_t and vendor_id <> v_s0;
    end;
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 506 (2025-02-02) → vendors.id 10 ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null then
    select id into v_t from qm_tadqiq where kashef_id = v_k and serial_no = '506' and tadqiq_date = date '2025-02-02' and note = 'استيراد تاريخي — الطرق السريعة' and not opening and vendor_id in (v_copri, v_s0) order by (vendor_id = v_s0) desc limit 1;
    if v_t is null then raise exception 'WO 3 طلب 506 missing — run 0051 first'; end if;
    begin
      update qm_tadqiq set vendor_id = v_s0 where id = v_t and vendor_id <> v_s0;
    end;
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 507 (2025-02-02) → vendors.id 10 ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null then
    select id into v_t from qm_tadqiq where kashef_id = v_k and serial_no = '507' and tadqiq_date = date '2025-02-02' and note = 'استيراد تاريخي — الطرق السريعة' and not opening and vendor_id in (v_copri, v_s0) order by (vendor_id = v_s0) desc limit 1;
    if v_t is null then raise exception 'WO 3 طلب 507 missing — run 0051 first'; end if;
    begin
      update qm_tadqiq set vendor_id = v_s0 where id = v_t and vendor_id <> v_s0;
    end;
  end if;

  -- ── أمر عمل 3 — طلب تدقيق 508 (2025-02-02) → vendors.id 10 ──
  select id into v_k from qm_kashefs where contract_id = v_contract and kashef_no = 3;
  if v_k is not null then
    select id into v_t from qm_tadqiq where kashef_id = v_k and serial_no = '508' and tadqiq_date = date '2025-02-02' and note = 'استيراد تاريخي — الطرق السريعة' and not opening and vendor_id in (v_copri, v_s0) order by (vendor_id = v_s0) desc limit 1;
    if v_t is null then raise exception 'WO 3 طلب 508 missing — run 0051 first'; end if;
    begin
      update qm_tadqiq set vendor_id = v_s0 where id = v_t and vendor_id <> v_s0;
    end;
  end if;

end $qmexpwex$;
