-- ════════════════════════════════════════════════════════════════════
-- 0062 — QUANTITIES: work-order description + scope taxonomy, and the
--        Expressway site clean-up (Fouad, 2026-08-17)
--
-- Generated by tools/qm_expw_site_clean.py — the per-WO mapping lives
-- there. Idempotent; safe to re-run. Paste after 0061 (independent).
--
--   A. qm_kashefs.description  — the ministry's own wording of the work
--      order. Shown ONLY on the WO page; the register/dashboard use the
--      short site fields. For the Expressway backfill this is where the
--      old cluttered `area` / `location_text` sentences go.
--   B. qm_kashefs.scopes text[] — MULTI-select scope of works, codes:
--        asphalt                    أسفلت
--        civil | storm | sewage | tiles   أعمال مدنية (عامة / أمطار / صحي / بلاط)
--        metal                      أعمال معدنية
--        other                      أخرى
--      `work_type` (free text) is KEPT as the printable label and is
--      rewritten from the scopes on save («أسفلت + أعمال معدنية»).
--   C. qm_kashef_create: +p_description, +p_scopes (old signature dropped,
--      as 0035/0049 did).
--   D. qm_kashef_update: learns 'description' and 'scopes' (scopes arrive
--      as a comma-separated code string — p_fields is text-valued).
--   E. qm_kashef_overview: description + scopes APPENDED (42P16).
--   G. Hawalli WOs get scopes from their legacy work_type (keyword map).
--   F. DATA — every Expressway WO re-keyed: area = طريق الفحيحيل /
--      طريق الملك فهد / a short «other» site; location_text = the km
--      range («من محطة 9+200 إلى محطة 12+200») or the spot name
--      («تقاطع (78) مع نادي الفحيحيل»); direction; description = the old
--      full sentence; scopes + work_type. Logged to qm_changelog with
--      actor 'expw-site-clean'.
-- ════════════════════════════════════════════════════════════════════

-- ── A + B. columns ───────────────────────────────────────────────────
alter table qm_kashefs add column if not exists description text   not null default '';
alter table qm_kashefs add column if not exists scopes      text[] not null default '{}';

do $qmsc$
begin
  if not exists (select 1 from pg_constraint con join pg_class rel on rel.oid = con.conrelid
                  where rel.relname = 'qm_kashefs' and con.conname = 'qm_kashefs_scopes_check') then
    alter table qm_kashefs add constraint qm_kashefs_scopes_check
      check (scopes <@ array['asphalt','civil','storm','sewage','tiles','metal','other']::text[]);
  end if;
end $qmsc$;

-- ── C. qm_kashef_create ──────────────────────────────────────────────
drop function if exists qm_kashef_create(text,int,text,text,text,text,text,jsonb,date,text,text,date,int,text,numeric,numeric,text);

create or replace function qm_kashef_create(
  p_contract_code text, p_kashef_no int, p_area text, p_loc_type text,
  p_block_no text, p_street_name text, p_work_type text,
  p_lines jsonb,
  p_kashef_date date default null,
  p_status text default 'wo', p_wo_no text default '', p_wo_date date default null,
  p_duration_days int default null,
  p_location_text text default '', p_km_from numeric default null,
  p_km_to numeric default null, p_direction text default '',
  p_description text default '', p_scopes text[] default '{}'
) returns json language plpgsql security definer set search_path = public as $qm$
declare
  v_contract qm_contracts;
  v_id bigint;
  v_line jsonb;
  v_item qm_bop_items;
  v_qty numeric;
  v_count int := 0;
begin
  if auth.uid() is null then return json_build_object('success', false, 'error', 'no session'); end if;
  select * into v_contract from qm_contracts where code = p_contract_code;
  if v_contract.id is null then return json_build_object('success', false, 'error', 'unknown contract'); end if;
  if p_loc_type not in ('block','street','misc','chainage') then
    return json_build_object('success', false, 'error', 'bad loc_type');
  end if;
  if p_loc_type = 'block' and coalesce(p_block_no, '') = '' then
    return json_build_object('success', false, 'error', 'block_no required');
  end if;
  if p_loc_type = 'street' and coalesce(p_street_name, '') = '' then
    return json_build_object('success', false, 'error', 'street_name required');
  end if;
  if p_loc_type = 'chainage' and coalesce(p_location_text, '') = '' then
    return json_build_object('success', false, 'error', 'location_text required');
  end if;
  if not (coalesce(p_scopes, '{}') <@ array['asphalt','civil','storm','sewage','tiles','metal','other']::text[]) then
    return json_build_object('success', false, 'error', 'bad scope');
  end if;
  if p_status not in ('kashef','wo') then
    return json_build_object('success', false, 'error', 'bad status');
  end if;
  if p_status = 'wo' and coalesce(p_wo_no, '') = '' then
    return json_build_object('success', false, 'error', 'wo_no required for wo status');
  end if;
  if p_lines is null or jsonb_typeof(p_lines) <> 'array' or jsonb_array_length(p_lines) = 0 then
    return json_build_object('success', false, 'error', 'no lines');
  end if;

  insert into qm_kashefs (contract_id, kashef_no, area, loc_type, block_no, street_name,
                          work_type, status, wo_no, wo_date, kashef_date, duration_days,
                          location_text, km_from, km_to, direction, description, scopes, created_by)
  values (v_contract.id, p_kashef_no, coalesce(p_area,''), p_loc_type,
          case when p_loc_type = 'block'  then coalesce(p_block_no,'')    else '' end,
          case when p_loc_type = 'street' then coalesce(p_street_name,'') else '' end,
          coalesce(p_work_type,''), p_status, coalesce(p_wo_no,''), p_wo_date,
          coalesce(p_kashef_date, p_wo_date, (now() at time zone 'Asia/Kuwait')::date),
          p_duration_days,
          case when p_loc_type = 'chainage' then coalesce(p_location_text,'') else '' end,
          case when p_loc_type = 'chainage' then p_km_from else null end,
          case when p_loc_type = 'chainage' then p_km_to   else null end,
          case when p_loc_type = 'chainage' then coalesce(p_direction,'')   else '' end,
          coalesce(p_description, ''), coalesce(p_scopes, '{}'),
          auth.uid())
  returning id into v_id;

  for v_line in select * from jsonb_array_elements(p_lines) loop
    select * into v_item from qm_bop_items
      where id = (v_line->>'bop_item_id')::bigint and contract_id = v_contract.id;
    if v_item.id is null then
      raise exception 'bop item % not found in contract', v_line->>'bop_item_id';
    end if;
    v_qty := (v_line->>'qty')::numeric;
    if v_qty is null or v_qty < 0 then
      raise exception 'bad qty for item %', qm_item_ref(v_item.id);
    end if;
    insert into qm_kashef_lines (kashef_id, bop_item_id, qty) values (v_id, v_item.id, v_qty);
    v_count := v_count + 1;
  end loop;

  perform qm_log('kashef', v_id, 'create', '', '',
                 '', 'أمر عمل ' || coalesce(nullif(p_wo_no,''), p_kashef_no::text) || ' — ' || v_count || ' بند');
  return json_build_object('success', true, 'id', v_id, 'lines', v_count);
exception when unique_violation then
  return json_build_object('success', false, 'error', 'kashef_no already exists');
end $qm$;

-- ── D. qm_kashef_update ──────────────────────────────────────────────
create or replace function qm_kashef_update(p_kashef_id bigint, p_fields jsonb)
returns json language plpgsql security definer set search_path = public as $qm$
declare
  v_k qm_kashefs;
  v_key text;
  v_new text;
  v_old text;
  v_changed int := 0;
  v_scopes text[];
begin
  if auth.uid() is null then return json_build_object('success', false, 'error', 'no session'); end if;
  select * into v_k from qm_kashefs where id = p_kashef_id;
  if v_k.id is null then return json_build_object('success', false, 'error', 'not found'); end if;

  for v_key in select jsonb_object_keys(p_fields) loop
    if v_key not in ('area','loc_type','block_no','street_name','work_type','kashef_no',
                     'kashef_date','wo_no','wo_date','duration_days','closed','daily_penalty',
                     'location_text','km_from','km_to','direction','description','scopes') then
      return json_build_object('success', false, 'error', 'field not editable: ' || v_key);
    end if;
  end loop;
  if p_fields ? 'loc_type' and p_fields->>'loc_type' not in ('block','street','misc','chainage') then
    return json_build_object('success', false, 'error', 'bad loc_type');
  end if;
  if p_fields ? 'closed' and p_fields->>'closed' not in ('true','false') then
    return json_build_object('success', false, 'error', 'bad closed');
  end if;
  if p_fields ? 'scopes' then
    v_scopes := coalesce(string_to_array(nullif(p_fields->>'scopes', ''), ','), '{}');
    if not (v_scopes <@ array['asphalt','civil','storm','sewage','tiles','metal','other']::text[]) then
      return json_build_object('success', false, 'error', 'bad scope');
    end if;
  end if;

  for v_key in select jsonb_object_keys(p_fields) loop
    v_new := p_fields->>v_key;
    v_old := case v_key
      when 'area' then v_k.area           when 'loc_type' then v_k.loc_type
      when 'block_no' then v_k.block_no   when 'street_name' then v_k.street_name
      when 'work_type' then v_k.work_type when 'kashef_no' then v_k.kashef_no::text
      when 'kashef_date' then v_k.kashef_date::text
      when 'wo_no' then v_k.wo_no         when 'wo_date' then coalesce(v_k.wo_date::text,'')
      when 'duration_days' then coalesce(v_k.duration_days::text,'')
      when 'closed' then v_k.closed::text
      when 'daily_penalty' then coalesce(v_k.daily_penalty::text,'')
      when 'location_text' then v_k.location_text
      when 'km_from' then coalesce(v_k.km_from::text,'')
      when 'km_to' then coalesce(v_k.km_to::text,'')
      when 'direction' then v_k.direction
      when 'description' then v_k.description
      when 'scopes' then array_to_string(v_k.scopes, ',')
    end;
    if coalesce(v_old,'') is distinct from coalesce(v_new,'') then
      if v_key = 'scopes' then
        update qm_kashefs set scopes = v_scopes where id = p_kashef_id;
      else
        execute format('update qm_kashefs set %I = $1::%s where id = $2', v_key,
                       case when v_key in ('kashef_no','duration_days') then 'int'
                            when v_key in ('kashef_date','wo_date') then 'date'
                            when v_key = 'closed' then 'boolean'
                            when v_key in ('daily_penalty','km_from','km_to') then 'numeric'
                            else 'text' end)
          using (case when v_key in ('wo_date','duration_days','daily_penalty','km_from','km_to')
                      then nullif(v_new, '') else v_new end),
                p_kashef_id;
      end if;
      perform qm_log('kashef', p_kashef_id, 'update', v_key, '', coalesce(v_old,''), coalesce(v_new,''));
      v_changed := v_changed + 1;
    end if;
  end loop;
  return json_build_object('success', true, 'changed', v_changed);
exception when unique_violation then
  return json_build_object('success', false, 'error', 'kashef_no already exists');
when others then
  return json_build_object('success', false, 'error', SQLERRM);
end $qm$;

-- ── E. qm_kashef_overview (+2 columns, APPENDED) ─────────────────────
create or replace view qm_kashef_overview
with (security_invoker = true) as
select k.id, k.contract_id, c.code as contract_code, c.pct,
       k.kashef_no, k.area, k.loc_type, k.block_no, k.street_name, k.work_type,
       k.status, k.wo_no, k.wo_date, k.kashef_date, k.created_at,
       coalesce(l.n, 0)                       as line_count,
       coalesce(l.subtotal, 0)                as subtotal,
       round(coalesce(l.subtotal, 0) * (1 + c.pct / 100), 3) as total_after_pct,
       coalesce(a.alloc_value, 0)             as allocated_value,
       coalesce(e.exec_value, 0)              as executed_value,
       coalesce(e.tadqiq_count, 0)            as tadqiq_count,
       k.duration_days,
       k.closed,
       c.contract_value,
       k.location_text,
       k.km_from,
       k.km_to,
       k.direction,
       k.description,                                    -- appended (42P16)
       k.scopes                                          -- appended
from qm_kashefs k
join qm_contracts c on c.id = k.contract_id
left join (
  select kl.kashef_id, count(*) as n, sum(kl.qty * bi.rate) as subtotal
  from qm_kashef_lines kl join qm_bop_items bi on bi.id = kl.bop_item_id
  group by kl.kashef_id
) l on l.kashef_id = k.id
left join (
  select kl.kashef_id, sum(al.qty * bi.rate) as alloc_value
  from qm_allocations al
  join qm_kashef_lines kl on kl.id = al.kashef_line_id
  join qm_bop_items bi on bi.id = kl.bop_item_id
  group by kl.kashef_id
) a on a.kashef_id = k.id
left join (
  select t.kashef_id, sum(tl.qty * bi.rate) as exec_value,
         count(distinct t.id) as tadqiq_count
  from qm_tadqiq t
  join qm_tadqiq_lines tl on tl.tadqiq_id = t.id
  join qm_bop_items bi on bi.id = tl.bop_item_id
  group by t.kashef_id
) e on e.kashef_id = k.id;

-- grants for the new qm_kashef_create signature
do $qmsc$
declare f text;
begin
  foreach f in array array[
    'qm_kashef_create(text,int,text,text,text,text,text,jsonb,date,text,text,date,int,text,numeric,numeric,text,text,text[])',
    'qm_kashef_update(bigint,jsonb)'
  ] loop
    execute format('revoke all on function %s from public, anon', f);
    execute format('grant execute on function %s to authenticated', f);
  end loop;
end $qmsc$;

-- ── F. Expressway site clean-up ──────────────────────────────────────
do $qmsc$
declare
  v_contract bigint;
  v_id bigint;
  v_n int := 0;
begin
  select id into v_contract from qm_contracts where code = 'EXPW';
  if v_contract is null then raise notice '0062: no EXPW contract, data step skipped'; return; end if;

  update qm_kashefs set
       area = 'طريق الملك فهد', loc_type = 'chainage', location_text = 'من محطة 7+000 إلى محطة 12+000',
       km_from = 7, km_to = 12, direction = 'بالاتجاهين',
       description = 'طريق الملك فهد من محطة 000+7 الى محطة 000+12 بالاتجاهين استبدال حواجز خرسانية + اعمال متفرقة بمسار الوفد', scopes = array['metal','other']::text[], work_type = 'أعمال معدنية + أخرى'
   where contract_id = v_contract and kashef_no = 1
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الملك فهد — من محطة 7+000 إلى محطة 12+000', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'أعمال معدنية', 'أعمال معدنية + أخرى', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'أعمال طارئة ومتفرقة', loc_type = 'misc', location_text = '',
       km_from = null, km_to = null, direction = '',
       description = 'اعمال طارئة ومتفرقة', scopes = array['other']::text[], work_type = 'أخرى'
   where contract_id = v_contract and kashef_no = 2
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'أعمال طارئة ومتفرقة — ', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'متفرقات', 'أخرى', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'مخرج صباح السالم',
       km_from = null, km_to = null, direction = '',
       description = 'طريق الفحيحيل مخرج صباح السالم من طرف طريق 30', scopes = array['other']::text[], work_type = 'أخرى'
   where contract_id = v_contract and kashef_no = 3
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — مخرج صباح السالم', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', '', 'أخرى', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'الملك فهد + الفحيحيل + النويصيب', loc_type = 'misc', location_text = '',
       km_from = null, km_to = null, direction = '',
       description = 'نظافة شبكة مياه الامطار طريق الملك فهد + الفحيحيل + النويصيب', scopes = array['storm']::text[], work_type = 'أمطار'
   where contract_id = v_contract and kashef_no = 4
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'الملك فهد + الفحيحيل + النويصيب — ', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'نظافة', 'أمطار', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'عند محطة 20+000',
       km_from = 20, km_to = null, direction = 'بالاتجاهين',
       description = 'طريق الفحيحيل عند محطة 000+20 بين الفنيطيس وابو الحصانية بالاتجاهين', scopes = array['other']::text[], work_type = 'أخرى'
   where contract_id = v_contract and kashef_no = 5
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — عند محطة 20+000', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', '', 'أخرى', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'من محطة 9+400 إلى محطة 12+100',
       km_from = 9.4, km_to = 12.1, direction = 'اتجاه الجنوب',
       description = 'صيانة اسفلت طريق الفحيحيل ازالة الحارة البطيئة وشولدر البطيئة من محطة 400+9 الى محطة 100+12 اتجاه الجنوب', scopes = array['asphalt']::text[], work_type = 'أسفلت'
   where contract_id = v_contract and kashef_no = 6
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — من محطة 9+400 إلى محطة 12+100', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'أسفلت', 'أسفلت', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'من محطة 9+200 إلى محطة 12+200',
       km_from = 9.2, km_to = 12.2, direction = 'اتجاه الجنوب',
       description = 'صيانة اسفلت طريق الفحيحيل من محطة 200+9 الى محطة 200+12 اتجاه الجنوب', scopes = array['asphalt']::text[], work_type = 'أسفلت'
   where contract_id = v_contract and kashef_no = 7
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — من محطة 9+200 إلى محطة 12+200', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'أسفلت', 'أسفلت', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'طريق الفحيحيل بالاتجاهين',
       km_from = null, km_to = null, direction = 'بالاتجاهين',
       description = 'طريق الفحيحيل بالاتجاهين', scopes = array['other']::text[], work_type = 'أخرى'
   where contract_id = v_contract and kashef_no = 9
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — طريق الفحيحيل بالاتجاهين', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', '', 'أخرى', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'من محطة 15+700 إلى محطة 12+000',
       km_from = 15.7, km_to = 12, direction = 'اتجاه الشمال',
       description = 'صيانة اسفلت طريق الفحيحيل من محطة 700+15 الى محطة 000+12 باتجاه الشمال', scopes = array['asphalt']::text[], work_type = 'أسفلت'
   where contract_id = v_contract and kashef_no = 10
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — من محطة 15+700 إلى محطة 12+000', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'أسفلت', 'أسفلت', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'أعمال طارئة ومتفرقة', loc_type = 'misc', location_text = '',
       km_from = null, km_to = null, direction = '',
       description = 'اعمال طارئة ومتفرقة', scopes = array['other']::text[], work_type = 'أخرى'
   where contract_id = v_contract and kashef_no = 11
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'أعمال طارئة ومتفرقة — ', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'متفرقات', 'أخرى', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'من محطة 13+400 إلى محطة 14+000',
       km_from = 13.4, km_to = 14, direction = 'اتجاه الجنوب',
       description = 'صيانة اسفلت طريق الفحيحيل من محطة 400+13 الى محطة 000+14 باتجاه الجنوب', scopes = array['asphalt']::text[], work_type = 'أسفلت'
   where contract_id = v_contract and kashef_no = 12
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — من محطة 13+400 إلى محطة 14+000', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'أسفلت', 'أسفلت', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'من محطة 9+200 إلى محطة 14+000',
       km_from = 9.2, km_to = 14, direction = 'اتجاه الجنوب',
       description = 'تخطيط ارضي لطريق الفحيحيل من محطة 200+9 الى محطة 200+12 ومن محطة 400+13 الى محطة 000+14 باتجاه الجنوب', scopes = array['other']::text[], work_type = 'أخرى'
   where contract_id = v_contract and kashef_no = 13
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — من محطة 9+200 إلى محطة 14+000', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'تخطيط أرضي', 'أخرى', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'من محطة 15+700 إلى محطة 12+000',
       km_from = 15.7, km_to = 12, direction = 'اتجاه الشمال',
       description = 'تخطيط ارضي لطريق الفحيحيل من محطة 700+15 الى محطة 000+12 باتجاه الشمال', scopes = array['other']::text[], work_type = 'أخرى'
   where contract_id = v_contract and kashef_no = 14
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — من محطة 15+700 إلى محطة 12+000', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'تخطيط أرضي', 'أخرى', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'أعمال طارئة ومتفرقة', loc_type = 'misc', location_text = '',
       km_from = null, km_to = null, direction = '',
       description = 'اعمال طارئة ومتفرقة', scopes = array['other']::text[], work_type = 'أخرى'
   where contract_id = v_contract and kashef_no = 15
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'أعمال طارئة ومتفرقة — ', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'متفرقات', 'أخرى', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'تقاطع (78) مع نادي الفحيحيل',
       km_from = null, km_to = null, direction = '',
       description = 'صيانة اسفلت لتقاطع (78) طريق الفحيحيل مع نادي الفحيحيل', scopes = array['asphalt']::text[], work_type = 'أسفلت'
   where contract_id = v_contract and kashef_no = 16
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — تقاطع (78) مع نادي الفحيحيل', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'أسفلت', 'أسفلت', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'من محطة 16+000 إلى محطة 17+000',
       km_from = 16, km_to = 17, direction = 'اتجاه الجنوب',
       description = 'صيانة اسفلت طريق الفحيحيل باتجاه الجنوب من محطة 000+16 الى محطة 000+17', scopes = array['asphalt']::text[], work_type = 'أسفلت'
   where contract_id = v_contract and kashef_no = 17
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — من محطة 16+000 إلى محطة 17+000', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'أسفلت', 'أسفلت', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'تقاطع (78) مع نادي الفحيحيل',
       km_from = null, km_to = null, direction = '',
       description = 'صيانة اسفلت لتقاطع ( 78 ) طريق الفحيحيل مع نادي الفحيحيل (الاعمال المدنية )', scopes = array['civil']::text[], work_type = 'أعمال مدنية'
   where contract_id = v_contract and kashef_no = 18
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — تقاطع (78) مع نادي الفحيحيل', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'أعمال مدنية', 'أعمال مدنية', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'من محطة 11+000 إلى محطة 5+000',
       km_from = 11, km_to = 5, direction = 'اتجاه الشمال',
       description = 'صيانة اسفلت طريق الفحيحل من محطة 000+11 الى محطة 000+5 اتجاه الشمال', scopes = array['asphalt']::text[], work_type = 'أسفلت'
   where contract_id = v_contract and kashef_no = 19
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — من محطة 11+000 إلى محطة 5+000', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'أسفلت', 'أسفلت', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'من محطة 11+000 إلى محطة 5+000',
       km_from = 11, km_to = 5, direction = '',
       description = 'بلاط متداخل بين الحواجز الخرسانية طريق الفحيحيل من محطة 000+11 الى محطة 000+5', scopes = array['tiles']::text[], work_type = 'بلاط'
   where contract_id = v_contract and kashef_no = 20
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — من محطة 11+000 إلى محطة 5+000', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'بلاط', 'بلاط', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'مدخل ومخرج سلوى',
       km_from = null, km_to = null, direction = '',
       description = 'مدخل ومخرج سلوى على طريق الفحيحيل ( الاعمال المدنية )', scopes = array['civil']::text[], work_type = 'أعمال مدنية'
   where contract_id = v_contract and kashef_no = 21
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — مدخل ومخرج سلوى', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'أعمال مدنية', 'أعمال مدنية', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'مستودعات الوزارة', loc_type = 'misc', location_text = '',
       km_from = null, km_to = null, direction = '',
       description = 'توريد واستلام حواجز بلاستيكية لمستودعات الوزارة', scopes = array['metal']::text[], work_type = 'أعمال معدنية'
   where contract_id = v_contract and kashef_no = 22
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'مستودعات الوزارة — ', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'أعمال معدنية', 'أعمال معدنية', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'منظومة قياس وزن الشاحنات', loc_type = 'misc', location_text = '',
       km_from = null, km_to = null, direction = '',
       description = 'منظومة قياس وزن الشاحنات (integrated Wight in motion system)', scopes = array['other']::text[], work_type = 'أخرى'
   where contract_id = v_contract and kashef_no = 23
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'منظومة قياس وزن الشاحنات — ', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'متفرقات', 'أخرى', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'من محطة 12+000 إلى محطة 5+000',
       km_from = 12, km_to = 5, direction = 'اتجاه الشمال',
       description = 'تخطيط ارضي لطريق الفحيحيل من محطة 000+12 الى محطة 000+5 باتجاه الشمال ( اعمال مدنية )', scopes = array['other']::text[], work_type = 'أخرى'
   where contract_id = v_contract and kashef_no = 24
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — من محطة 12+000 إلى محطة 5+000', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'تخطيط أرضي', 'أخرى', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'من محطة 11+000 إلى محطة 10+000',
       km_from = 11, km_to = 10, direction = 'اتجاه الكويت',
       description = 'صيانة واستبدال البلاط وحجر الرصيف على طريق الفحيحيل من محطة 000+11 الى محطة 000+10 باتجاه الكويت', scopes = array['tiles']::text[], work_type = 'بلاط'
   where contract_id = v_contract and kashef_no = 25
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — من محطة 11+000 إلى محطة 10+000', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'بلاط', 'بلاط', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'من محطة 16+000 إلى محطة 17+000',
       km_from = 16, km_to = 17, direction = 'اتجاه الجنوب',
       description = 'تخطيط ارضي لطريق الفحيحيل من محطة 000+16 الى محطة 000+17 باتجاه الجنوب', scopes = array['other']::text[], work_type = 'أخرى'
   where contract_id = v_contract and kashef_no = 26
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — من محطة 16+000 إلى محطة 17+000', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'تخطيط أرضي', 'أخرى', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الملك عبد العزيز', loc_type = 'chainage', location_text = 'تقاطع (86)',
       km_from = null, km_to = null, direction = 'اتجاه الجنوب',
       description = 'طريق الملك عبد العزيز السريع تقاطع 86 - اتجاه الجنوب', scopes = array['other']::text[], work_type = 'أخرى'
   where contract_id = v_contract and kashef_no = 27
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الملك عبد العزيز — تقاطع (86)', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'متفرقات', 'أخرى', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'الشعيبة الصناعية', loc_type = 'misc', location_text = '',
       km_from = null, km_to = null, direction = '',
       description = 'صيانة مناهيل امطار بمنطقة الشعيبة الصناعية', scopes = array['storm']::text[], work_type = 'أمطار'
   where contract_id = v_contract and kashef_no = 28
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'الشعيبة الصناعية — ', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'أمطار', 'أمطار', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'الطريق الساحلي', loc_type = 'chainage', location_text = 'مدخل بعد فندق السفير',
       km_from = null, km_to = null, direction = '',
       description = 'مدخل على الطريق الساحلي بعد فندق السفير', scopes = array['other']::text[], work_type = 'أخرى'
   where contract_id = v_contract and kashef_no = 29
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'الطريق الساحلي — مدخل بعد فندق السفير', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', '', 'أخرى', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق أم صفق', loc_type = 'misc', location_text = '',
       km_from = null, km_to = null, direction = '',
       description = 'طوارئ امطار الباب الاول + نظافة الرمال طريق ام صفق', scopes = array['storm','other']::text[], work_type = 'أمطار + أخرى'
   where contract_id = v_contract and kashef_no = 30
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق أم صفق — ', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'نظافة', 'أمطار + أخرى', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'أعمال طارئة ومتفرقة', loc_type = 'misc', location_text = '',
       km_from = null, km_to = null, direction = '',
       description = 'اعمال طارئة ومتفرقة', scopes = array['other']::text[], work_type = 'أخرى'
   where contract_id = v_contract and kashef_no = 31
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'أعمال طارئة ومتفرقة — ', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'متفرقات', 'أخرى', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'تقاطع (78) مع نادي الفحيحيل',
       km_from = null, km_to = null, direction = '',
       description = 'تخطيط ارضي لتقاطع ( 78 )', scopes = array['other']::text[], work_type = 'أخرى'
   where contract_id = v_contract and kashef_no = 32
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — تقاطع (78) مع نادي الفحيحيل', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'تخطيط أرضي', 'أخرى', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'من محطة 1+200 إلى محطة 2+700',
       km_from = 1.2, km_to = 2.7, direction = 'اتجاه الفحيحيل',
       description = 'طريق الفحيحيل من كيلو 200+1 الى 700+2 (صيانة اسفلت) اتجاه الفحيحيل', scopes = array['asphalt']::text[], work_type = 'أسفلت'
   where contract_id = v_contract and kashef_no = 33
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — من محطة 1+200 إلى محطة 2+700', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'أسفلت', 'أسفلت', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'تقاطع (16) مع الدائري الرابع',
       km_from = null, km_to = null, direction = '',
       description = 'صيانة لوبات تقاطع ( 16 ) الدائري الرابع مع الفحيحيل ( اعمال اسفلت )', scopes = array['asphalt']::text[], work_type = 'أسفلت'
   where contract_id = v_contract and kashef_no = 34
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — تقاطع (16) مع الدائري الرابع', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'أسفلت', 'أسفلت', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'تقاطع (16) مع الدائري الرابع',
       km_from = null, km_to = null, direction = '',
       description = 'تخطيط ارضي للوبات تقاطع 16 (الدائري الرابع مع طريق الفحيحيل)', scopes = array['other']::text[], work_type = 'أخرى'
   where contract_id = v_contract and kashef_no = 35
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — تقاطع (16) مع الدائري الرابع', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'تخطيط أرضي', 'أخرى', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'تقاطع (16) مع الدائري الرابع',
       km_from = null, km_to = null, direction = '',
       description = 'صيانة تقاطع 16 - الدائري الرابع مع الفحيحيل ( الاعمال المدنية )', scopes = array['civil']::text[], work_type = 'أعمال مدنية'
   where contract_id = v_contract and kashef_no = 36
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — تقاطع (16) مع الدائري الرابع', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'أعمال مدنية', 'أعمال مدنية', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'الجسور', loc_type = 'misc', location_text = '',
       km_from = null, km_to = null, direction = '',
       description = 'متفرقات- فواصل التمدد للجسور (5-8-15-36-36A)', scopes = array['civil']::text[], work_type = 'أعمال مدنية'
   where contract_id = v_contract and kashef_no = 37
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'الجسور — ', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'جسور', 'أعمال مدنية', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'تقاطع (76A) مع نادي الساحل',
       km_from = null, km_to = null, direction = '',
       description = 'طريق الفحيحيل مع نادي الساحل تقاطع (76A) اعمال اسفلت', scopes = array['asphalt']::text[], work_type = 'أسفلت'
   where contract_id = v_contract and kashef_no = 38
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — تقاطع (76A) مع نادي الساحل', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'أسفلت', 'أسفلت', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'من محطة 0+000 إلى محطة 5+000',
       km_from = 0, km_to = 5, direction = 'اتجاه الجنوب',
       description = 'صيانة واستبدال بلاط وحجر رصيف على طريق الفحيحيل من محطة 000+00 الى محطة 00+5 باتجاه الجنوب', scopes = array['tiles']::text[], work_type = 'بلاط'
   where contract_id = v_contract and kashef_no = 39
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — من محطة 0+000 إلى محطة 5+000', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'بلاط', 'بلاط', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'من محطة 0+000 إلى محطة 5+000',
       km_from = 0, km_to = 5, direction = 'اتجاه الجنوب',
       description = 'صيانة واستبدال الاعمال المعدنية ( شبك+حواجز حديدية ) على طريق الفحيحيل من محطة 000+00 الى محطة 000+5 باتجاه الجنوب', scopes = array['metal']::text[], work_type = 'أعمال معدنية'
   where contract_id = v_contract and kashef_no = 40
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — من محطة 0+000 إلى محطة 5+000', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'أعمال معدنية', 'أعمال معدنية', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'من محطة 0+000 إلى محطة 3+300',
       km_from = 0, km_to = 3.3, direction = 'اتجاه الجنوب',
       description = 'تخطيط ارضي وعلامات مرورية من محطة 000+000 الى محطة 300+3 طريق الفحيحيل باتجاه الجنوب', scopes = array['other']::text[], work_type = 'أخرى'
   where contract_id = v_contract and kashef_no = 41
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — من محطة 0+000 إلى محطة 3+300', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'تخطيط أرضي', 'أخرى', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'من محطة 11+000 إلى محطة 5+000',
       km_from = 11, km_to = 5, direction = '',
       description = 'بلاط متداخل بين الحواجز الخرسانية طريق الفحيحيل من محطة 000+11 الى محطة 000+5', scopes = array['tiles']::text[], work_type = 'بلاط'
   where contract_id = v_contract and kashef_no = 42
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — من محطة 11+000 إلى محطة 5+000', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'بلاط', 'بلاط', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'من محطة 18+000 إلى محطة 25+000',
       km_from = 18, km_to = 25, direction = 'اتجاه الجنوب',
       description = 'صيانة اسفلت طريق الفحيحيل من محطة 000+18 الى 000+25 باتجاه الجنوب', scopes = array['asphalt']::text[], work_type = 'أسفلت'
   where contract_id = v_contract and kashef_no = 43
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — من محطة 18+000 إلى محطة 25+000', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'أسفلت', 'أسفلت', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'الملك فهد + الفحيحيل', loc_type = 'misc', location_text = '',
       km_from = null, km_to = null, direction = '',
       description = 'نظافة شبكة مياه الامطار طريق الملك فهد وطريق الفحيحيل السريع', scopes = array['storm']::text[], work_type = 'أمطار'
   where contract_id = v_contract and kashef_no = 44
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'الملك فهد + الفحيحيل — ', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'نظافة', 'أمطار', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'الفنيطيس', loc_type = 'misc', location_text = '',
       km_from = null, km_to = null, direction = '',
       description = 'تركيب حاجز جلفنايز بمنطقة الفنيطيس قطعة 8 شارع 812 منزل 258', scopes = array['metal']::text[], work_type = 'أعمال معدنية'
   where contract_id = v_contract and kashef_no = 45
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'الفنيطيس — ', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'متفرقات', 'أعمال معدنية', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'تقاطع (76A) مع نادي الساحل',
       km_from = null, km_to = null, direction = '',
       description = 'تخطيط ارضي طريق الفحيحيل مع نادي الساحل 76A', scopes = array['other']::text[], work_type = 'أخرى'
   where contract_id = v_contract and kashef_no = 46
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — تقاطع (76A) مع نادي الساحل', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'تخطيط أرضي', 'أخرى', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'تقاطع (76A) مع نادي الساحل',
       km_from = null, km_to = null, direction = '',
       description = 'اعمال تعديل شبكة الامطار طريق الفحيحيل مع نادي الساحل ( 76A )', scopes = array['storm']::text[], work_type = 'أمطار'
   where contract_id = v_contract and kashef_no = 47
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — تقاطع (76A) مع نادي الساحل', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'أمطار', 'أمطار', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'أماكن متفرقة', loc_type = 'misc', location_text = '',
       km_from = null, km_to = null, direction = '',
       description = 'طوارئ متفرقة ( أماكن متفرقة )', scopes = array['other']::text[], work_type = 'أخرى'
   where contract_id = v_contract and kashef_no = 48
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'أماكن متفرقة — ', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'متفرقات', 'أخرى', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الملك فهد', loc_type = 'chainage', location_text = 'طريق الملك فهد',
       km_from = null, km_to = null, direction = '',
       description = 'صيانة حواجز حديدية في اماكن متفرقة على طريق الملك فهد', scopes = array['metal']::text[], work_type = 'أعمال معدنية'
   where contract_id = v_contract and kashef_no = 49
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الملك فهد — طريق الملك فهد', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'أعمال معدنية', 'أعمال معدنية', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'تقاطع (76A) مع نادي الساحل',
       km_from = null, km_to = null, direction = '',
       description = 'صيانة تقاطع 76A على طريق الفحيحيل مع نادي الساحل ( الاعمال المدنية )', scopes = array['civil']::text[], work_type = 'أعمال مدنية'
   where contract_id = v_contract and kashef_no = 50
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — تقاطع (76A) مع نادي الساحل', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'أعمال مدنية', 'أعمال مدنية', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'أعمال طارئة ومتفرقة', loc_type = 'misc', location_text = '',
       km_from = null, km_to = null, direction = '',
       description = 'اعمال طارئة ومتفرقة', scopes = array['other']::text[], work_type = 'أخرى'
   where contract_id = v_contract and kashef_no = 51
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'أعمال طارئة ومتفرقة — ', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'متفرقات', 'أخرى', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'من محطة 17+000 إلى محطة 25+800',
       km_from = 17, km_to = 25.8, direction = '',
       description = 'تخطيط ارضي لطريق الفحيحيل من محطة 000+17 الى محطة 800+25', scopes = array['other']::text[], work_type = 'أخرى'
   where contract_id = v_contract and kashef_no = 52
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — من محطة 17+000 إلى محطة 25+800', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'تخطيط أرضي', 'أخرى', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'الطريق الساحلي', loc_type = 'chainage', location_text = 'مدخل بعد فندق السفير + أماكن متفرقة على طريق الفحيحيل',
       km_from = null, km_to = null, direction = '',
       description = 'تخطيط ارضي مدخل على الطريق الساحلي بعد فندق السفير+ أماكن متفرقة على طريق الفحيحيل', scopes = array['other']::text[], work_type = 'أخرى'
   where contract_id = v_contract and kashef_no = 53
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'الطريق الساحلي — مدخل بعد فندق السفير + أماكن متفرقة على طريق الفحيحيل', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'تخطيط أرضي', 'أخرى', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'عند محطة 20+000',
       km_from = 20, km_to = null, direction = '',
       description = 'طريق الفحيحيل (30) عند محطة 000+20 بين الفنيطيس وأبو الحصانية لحل مشكلة تجمع مياه الامطار', scopes = array['storm']::text[], work_type = 'أمطار'
   where contract_id = v_contract and kashef_no = 54
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — عند محطة 20+000', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'أمطار', 'أمطار', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'تقاطع الفحيحيل مع الدائري السابع',
       km_from = null, km_to = null, direction = '',
       description = 'اعمال توريد وتركيب حاجب الرؤية على تقاطع الفحيحيل مع الدائري السابع', scopes = array['metal']::text[], work_type = 'أعمال معدنية'
   where contract_id = v_contract and kashef_no = 55
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — تقاطع الفحيحيل مع الدائري السابع', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'متفرقات', 'أعمال معدنية', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'أعمال طارئة ومتفرقة', loc_type = 'misc', location_text = '',
       km_from = null, km_to = null, direction = '',
       description = 'طوارئ امطار', scopes = array['storm']::text[], work_type = 'أمطار'
   where contract_id = v_contract and kashef_no = 56
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'أعمال طارئة ومتفرقة — ', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'أمطار', 'أمطار', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'من محطة 26+500 إلى محطة 27+000',
       km_from = 26.5, km_to = 27, direction = 'اتجاه الجنوب',
       description = 'صيانة اسفلت طريق الفحيحيل (من محطة500+26 الى محطة 000+27 ومن 500+32 الى 700+33 اتجاه جنوب ) (من 500+32 الى 700+33 اتجاه الشمال )', scopes = array['asphalt']::text[], work_type = 'أسفلت'
   where contract_id = v_contract and kashef_no = 57
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — من محطة 26+500 إلى محطة 27+000', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'أسفلت', 'أسفلت', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'مدخل ومخرج السفارات',
       km_from = null, km_to = null, direction = 'اتجاه الشمال',
       description = 'مدخل ومخرج السفارات على طريق الفحيحيل اتجاه الشمال', scopes = array['other']::text[], work_type = 'أخرى'
   where contract_id = v_contract and kashef_no = 58
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — مدخل ومخرج السفارات', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', '', 'أخرى', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'أعمال طارئة ومتفرقة', loc_type = 'misc', location_text = '',
       km_from = null, km_to = null, direction = '',
       description = 'اعمال طارئة ومتفرقة', scopes = array['other']::text[], work_type = 'أخرى'
   where contract_id = v_contract and kashef_no = 59
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'أعمال طارئة ومتفرقة — ', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'متفرقات', 'أخرى', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'أعمال طارئة ومتفرقة', loc_type = 'misc', location_text = '',
       km_from = null, km_to = null, direction = '',
       description = 'اعمال طارئة ومتفرقة', scopes = array['other']::text[], work_type = 'أخرى'
   where contract_id = v_contract and kashef_no = 60
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'أعمال طارئة ومتفرقة — ', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'متفرقات', 'أخرى', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الملك فهد', loc_type = 'chainage', location_text = 'من محطة 0+000 إلى محطة 3+500',
       km_from = 0, km_to = 3.5, direction = 'اتجاه الجنوب',
       description = 'صيانه اسفلت طريق الملك فهد من محطه (000+00الي 500+3)اتجاه الجنوب', scopes = array['asphalt']::text[], work_type = 'أسفلت'
   where contract_id = v_contract and kashef_no = 63
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الملك فهد — من محطة 0+000 إلى محطة 3+500', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'أسفلت', 'أسفلت', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'تقاطع طريق 30 مع طريق 207',
       km_from = null, km_to = null, direction = '',
       description = 'أعمال بلاط تقاطع طريق 30 مع طريق 207 وأعمال دهان حواجز مقابل برج التحكم', scopes = array['tiles','other']::text[], work_type = 'بلاط + أخرى'
   where contract_id = v_contract and kashef_no = 64
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — تقاطع طريق 30 مع طريق 207', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'بلاط', 'بلاط + أخرى', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'من بداية طريق الاستقلال حتى تقاطع (15)',
       km_from = null, km_to = null, direction = '',
       description = 'من بدايه طريق الاستقلال (طريق 30) حتي نهايه الجزيره الوسطي وبدايه الحواجز الخرسانيه تقاطع (15) ازاله حواجز حديديه', scopes = array['metal']::text[], work_type = 'أعمال معدنية'
   where contract_id = v_contract and kashef_no = 65
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — من بداية طريق الاستقلال حتى تقاطع (15)', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'أعمال معدنية', 'أعمال معدنية', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'من محطة 26+500 إلى محطة 27+000',
       km_from = 26.5, km_to = 27, direction = 'اتجاه الجنوب',
       description = 'تخطيط ارضي طريق الفحيحيل (من محطه 500+26 الي 000+27 ومن 500+32 الي 700+33 اتجاه الجنوب )', scopes = array['other']::text[], work_type = 'أخرى'
   where contract_id = v_contract and kashef_no = 66
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — من محطة 26+500 إلى محطة 27+000', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'تخطيط أرضي', 'أخرى', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'طريق الفحيحيل', loc_type = 'chainage', location_text = 'طريق الفحيحيل بالاتجاهين',
       km_from = null, km_to = null, direction = 'بالاتجاهين',
       description = 'اصلاح مكان انقلاب تنكر الديزل علي طريق الفحيحيل اتجاه الشمال والجنوب', scopes = array['asphalt']::text[], work_type = 'أسفلت'
   where contract_id = v_contract and kashef_no = 67
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'طريق الفحيحيل — طريق الفحيحيل بالاتجاهين', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', '', 'أسفلت', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;

  update qm_kashefs set
       area = 'أعمال طارئة ومتفرقة', loc_type = 'misc', location_text = '',
       km_from = null, km_to = null, direction = '',
       description = 'اعمال طارئة ومتفرقة', scopes = array['other']::text[], work_type = 'أخرى'
   where contract_id = v_contract and kashef_no = 68
   returning id into v_id;
  if v_id is not null then
    insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
    values ('kashef', v_id, 'update', 'site', '', '', 'أعمال طارئة ومتفرقة — ', 'expw-site-clean'),
           ('kashef', v_id, 'update', 'scopes', '', 'متفرقات', 'أخرى', 'expw-site-clean');
    v_n := v_n + 1;
  end if;
  v_id := null;
  raise notice '0062: % Expressway work orders re-keyed', v_n;
end $qmsc$;

-- ── G. Hawalli: scopes from the legacy work_type (keyword map) ───────
-- Only rows still carrying no scopes; work_type text is left untouched.
-- Backfill values seen: أعمال مدنية / صحي / أسفلت / متفرقات / اخرى / أمطار / ''.
do $qmsc$
declare
  v_contract bigint;
  r record;
  v_scopes text[];
  v_n int := 0;
begin
  select id into v_contract from qm_contracts where code = 'HAW9';
  if v_contract is null then return; end if;
  for r in select id, work_type from qm_kashefs
            where contract_id = v_contract and coalesce(scopes, '{}') = '{}' loop
    v_scopes := '{}';
    if r.work_type ~ 'سفلت'                 then v_scopes := array_append(v_scopes, 'asphalt'); end if;
    if r.work_type ~ 'معدني'                then v_scopes := array_append(v_scopes, 'metal');   end if;
    if r.work_type ~ 'مطار'                 then v_scopes := array_append(v_scopes, 'storm');   end if;
    if r.work_type ~ 'صحي'                  then v_scopes := array_append(v_scopes, 'sewage');  end if;
    if r.work_type ~ 'بلاط|انترلوك|طابوق'   then v_scopes := array_append(v_scopes, 'tiles');   end if;
    if r.work_type ~ 'مدني'                 then v_scopes := array_append(v_scopes, 'civil');   end if;
    if v_scopes = '{}' and r.work_type <> '' then v_scopes := array['other']; end if;
    if v_scopes <> '{}' then
      update qm_kashefs set scopes = v_scopes where id = r.id;
      insert into qm_changelog (entity, entity_id, action, field, line_ref, old_value, new_value, actor_email)
      values ('kashef', r.id, 'update', 'scopes', '', r.work_type, array_to_string(v_scopes, ','), 'haw9-scopes');
      v_n := v_n + 1;
    end if;
  end loop;
  raise notice '0062: % Hawalli work orders given scopes', v_n;
end $qmsc$;
